begin;
create temporary table phase8_before as select(select count(*)from public.financial_payments)payments,(select count(*)from public.account_moves where state='posted')moves,(select count(*)from public.account_move_lines where parent_state='posted')lines,(select count(*)from public.account_partial_reconcile)partials,(select coalesce(sum(debit),0)from public.account_move_lines where parent_state='posted')debit,(select coalesce(sum(credit),0)from public.account_move_lines where parent_state='posted')credit;
create temporary table phase8_context as select o.tenant_id,o.id owner_id,o.auth_user_id owner_auth,u.id other_id,u.auth_user_id other_auth,public.resolve_financial_journal(o.tenant_id,'general',null,null)journal_id from public.tenant_users o join lateral(select x.*from public.tenant_users x where x.tenant_id=o.tenant_id and x.is_active and x.role<>'owner'and x.auth_user_id is not null limit 1)u on true where o.role='owner'and o.is_active and o.auth_user_id is not null limit 1;
do $$begin if not exists(select 1 from phase8_context)then raise exception'PHASE8_FIXTURE_UNAVAILABLE';end if;end$$;
create temporary table phase8_resources(branch uuid,customer uuid,other_customer uuid,supplier uuid,method uuid,destination uuid,cash uuid,ar uuid,ca uuid,ap uuid,sa uuid,ar_source uuid,advance_source uuid,ap_source uuid,supplier_advance_source uuid,applied_advance_source uuid,original_payment uuid);
grant select,update on phase8_resources to public;grant select on phase8_context to public;
do $$declare c phase8_context%rowtype;r phase8_resources%rowtype;g uuid;s text:=left(replace(gen_random_uuid()::text,'-',''),8);gid uuid;begin select*into c from phase8_context;select id into g from public.account_groups where tenant_id=c.tenant_id limit 1;r.branch:=gen_random_uuid();insert into public.branches(id,tenant_id,name,code,is_active)values(r.branch,c.tenant_id,'Phase8 Branch','P8'||left(s,5),true);
 insert into public.partners(tenant_id,name,contact_type,is_company,is_external_contact,customer_rank,supplier_rank,financer_rank,active)values(c.tenant_id,'P8 Customer','person',false,true,1,0,0,true)returning id into r.customer;insert into public.partners(tenant_id,name,contact_type,is_company,is_external_contact,customer_rank,supplier_rank,financer_rank,active)values(c.tenant_id,'P8 Other Customer','person',false,true,1,0,0,true)returning id into r.other_customer;insert into public.partners(tenant_id,name,contact_type,is_company,is_external_contact,customer_rank,supplier_rank,financer_rank,active)values(c.tenant_id,'P8 Supplier','company',true,true,0,1,0,true)returning id into r.supplier;
 insert into public.financial_payment_methods(tenant_id,name,semantic_key,method_type,requires_confirmation,created_by)values(c.tenant_id,'P8 Cash','p8_'||s,'cash',false,c.owner_id)returning id into r.method;
 insert into public.account_accounts(tenant_id,group_id,code,name,account_type,reconcile,active,canonical_account_type,statement_section,reporting_category,normal_balance,open_item_reconcile,statement_reconcile,is_posting,semantic_key,template_account_key,account_origin)values(c.tenant_id,g,'P8AR'||s,'P8 AR','asset',true,true,'receivable','balance_sheet','trade_receivables','debit',true,false,true,'p8_ar_'||s,'p8_ar_'||s,'template')returning id into r.ar;
 insert into public.account_accounts(tenant_id,group_id,code,name,account_type,reconcile,active,canonical_account_type,statement_section,reporting_category,normal_balance,open_item_reconcile,statement_reconcile,is_posting,semantic_key,template_account_key,account_origin)values(c.tenant_id,g,'P8CA'||s,'P8 Customer Advance','liability',true,true,'current_liability','balance_sheet','customer_advances','credit',true,false,true,'p8_ca_'||s,'p8_ca_'||s,'template')returning id into r.ca;
 insert into public.account_accounts(tenant_id,group_id,code,name,account_type,reconcile,active,canonical_account_type,statement_section,reporting_category,normal_balance,open_item_reconcile,statement_reconcile,is_posting,semantic_key,template_account_key,account_origin)values(c.tenant_id,g,'P8AP'||s,'P8 AP','liability',true,true,'payable','balance_sheet','trade_payables','credit',true,false,true,'p8_ap_'||s,'p8_ap_'||s,'template')returning id into r.ap;
 insert into public.account_accounts(tenant_id,group_id,code,name,account_type,reconcile,active,canonical_account_type,statement_section,reporting_category,normal_balance,open_item_reconcile,statement_reconcile,is_posting,semantic_key,template_account_key,account_origin)values(c.tenant_id,g,'P8SA'||s,'P8 Supplier Advance','asset',true,true,'current_asset','balance_sheet','other_receivables','debit',true,false,true,'p8_sa_'||s,'p8_sa_'||s,'template')returning id into r.sa;
 update public.account_functional_accounts set is_active=false where tenant_id=c.tenant_id and functional_role in('customer_receivable','customer_advance','supplier_payable','supplier_advance')and is_active;insert into public.account_functional_accounts(tenant_id,functional_role,account_id)values(c.tenant_id,'customer_receivable',r.ar),(c.tenant_id,'customer_advance',r.ca),(c.tenant_id,'supplier_payable',r.ap),(c.tenant_id,'supplier_advance',r.sa);
 insert into public.res_groups(tenant_id,name,code,category,is_system,active)values(c.tenant_id,'P8 actors','p8_'||s,'Tenant',false,true)returning id into gid;insert into public.auth_group_permissions(group_id,permission_id)select gid,id from public.auth_permissions where code like'financial.refund.%'or code='financial.destination.manage';insert into public.res_users_groups(tenant_id,user_id,group_id)values(c.tenant_id,c.owner_id,gid);insert into phase8_resources values(r.*);end$$;
select set_config('request.jwt.claim.sub',owner_auth::text,true)from phase8_context;set local role authenticated;
do $$declare c phase8_context%rowtype;r phase8_resources%rowtype;x jsonb;begin select*into c from phase8_context;select*into r from phase8_resources;x:=public.create_and_provision_money_destination(c.tenant_id,'p8_cash','P8 Cashbox','cashbox',r.branch,null,null,null,null,null,'{}',true);update phase8_resources set destination=(x->>'destination_id')::uuid,cash=(x->>'account_id')::uuid;end$$;set local role postgres;

-- Posted refundable bases. The counterpart is fixture-only and never interpreted as revenue/credit-note creation.
do $$declare c phase8_context%rowtype;r phase8_resources%rowtype;mid uuid;counter uuid;i int;acct uuid;partner uuid;amount numeric;is_debit boolean;line uuid;begin select*into c from phase8_context;select*into r from phase8_resources;for i in 1..5 loop acct:=case i when 1 then r.ar when 2 then r.ca when 3 then r.ap when 4 then r.sa else r.ca end;partner:=case when i in(1,2,5)then r.customer else r.supplier end;amount:=case when i=3 then 10000 else 20000 end;is_debit:=i in(3,4);mid:=gen_random_uuid();insert into public.account_moves(id,tenant_id,branch_id,journal_id,name,move_type,partner_id,invoice_date,date,amount_total,state,ref,currency_code,created_by)values(mid,c.tenant_id,r.branch,c.journal_id,'P8 SOURCE','journal',partner,current_date,current_date,amount,'posted','phase8_refundable_source','EGP',c.owner_id);insert into public.account_move_lines(tenant_id,move_id,account_id,partner_id,label,quantity,unit_price,debit,credit,line_type,is_reconciled,amount_residual,amount_residual_currency,parent_state,currency_code,created_by)values(c.tenant_id,mid,acct,partner,'Refundable source',1,amount,case when is_debit then amount else 0 end,case when is_debit then 0 else amount end,'open_item',false,amount,amount,'posted','EGP',c.owner_id)returning id into line;insert into public.account_move_lines(tenant_id,move_id,account_id,label,quantity,unit_price,debit,credit,line_type,is_reconciled,amount_residual,amount_residual_currency,parent_state,currency_code,created_by)values(c.tenant_id,mid,r.cash,'Fixture counterpart',1,amount,case when is_debit then 0 else amount end,case when is_debit then amount else 0 end,'other',true,0,0,'posted','EGP',c.owner_id);if i=1 then r.ar_source:=line;elsif i=2 then r.advance_source:=line;elsif i=3 then r.ap_source:=line;elsif i=4 then r.supplier_advance_source:=line;else r.applied_advance_source:=line;end if;end loop;
 -- Consume 12k of the last advance to model a canonical applied portion; residual truth becomes 8k.
 mid:=gen_random_uuid();insert into public.account_moves(id,tenant_id,branch_id,journal_id,name,move_type,partner_id,invoice_date,date,amount_total,state,ref,currency_code,created_by)values(mid,c.tenant_id,r.branch,c.journal_id,'P8 APPLICATION','journal',r.customer,current_date,current_date,12000,'posted','phase8_applied_advance','EGP',c.owner_id);insert into public.account_move_lines(tenant_id,move_id,account_id,partner_id,label,quantity,unit_price,debit,credit,line_type,is_reconciled,amount_residual,amount_residual_currency,parent_state,currency_code,created_by)values(c.tenant_id,mid,r.ca,r.customer,'Applied advance debit',1,12000,12000,0,'open_item',false,12000,12000,'posted','EGP',c.owner_id)returning id into counter;insert into public.account_move_lines(tenant_id,move_id,account_id,label,quantity,unit_price,debit,credit,line_type,is_reconciled,amount_residual,amount_residual_currency,parent_state,currency_code,created_by)values(c.tenant_id,mid,r.cash,'Counterpart',1,12000,0,12000,'other',true,0,0,'posted','EGP',c.owner_id);insert into public.account_partial_reconcile(tenant_id,debit_move_id,credit_move_id,amount,max_date,created_by)values(c.tenant_id,counter,r.applied_advance_source,12000,current_date,c.owner_id);
 insert into public.financial_payments(tenant_id,payment_number,direction,amount,currency_code,payment_method_id,partner_id,status,idempotency_key,request_fingerprint,created_by,submitted_by,submitted_at,confirmed_by,confirmed_at)values(c.tenant_id,'PAY-2026-980001','inbound',20000,'EGP',r.method,r.customer,'confirmed','p8-original-payment',repeat('a',64),c.owner_id,c.owner_id,now(),c.owner_id,now())returning id into r.original_payment;update phase8_resources set ar_source=r.ar_source,advance_source=r.advance_source,ap_source=r.ap_source,supplier_advance_source=r.supplier_advance_source,applied_advance_source=r.applied_advance_source,original_payment=r.original_payment;end$$;

select set_config('request.jwt.claim.sub',owner_auth::text,true)from phase8_context;set local role authenticated;
do $$declare c phase8_context%rowtype;r phase8_resources%rowtype;x jsonb;y jsonb;rid uuid;mid uuid;cash0 numeric;begin select*into c from phase8_context;select*into r from phase8_resources;select coalesce(sum(debit-credit),0)into cash0 from public.account_move_lines where account_id=r.cash;
 -- AR partial and multiple refunds: 20 -> 15 -> 8.
 x:=public.create_financial_refund(c.tenant_id,r.ar_source,r.customer,5000,'EGP',r.destination,r.method,'AR credit refund','p8-ar-1',r.branch,r.original_payment);rid:=(x->>'refund_id')::uuid;perform public.submit_financial_refund(c.tenant_id,rid);perform public.confirm_financial_refund(c.tenant_id,rid);x:=public.post_financial_refund(c.tenant_id,rid,'p8-ar-post-1');mid:=(x->>'account_move_id')::uuid;if(select debit from public.account_move_lines where move_id=mid and account_id=r.ar)<>5000 or(select credit from public.account_move_lines where move_id=mid and account_id=r.cash)<>5000 or(select amount_residual from public.account_move_lines where id=r.ar_source)<>15000 then raise exception'AR_REFUND_INVALID';end if;
 x:=public.create_financial_refund(c.tenant_id,r.ar_source,r.customer,7000,'EGP',r.destination,r.method,'Second AR refund','p8-ar-2',r.branch);rid:=(x->>'refund_id')::uuid;perform public.submit_financial_refund(c.tenant_id,rid);perform public.confirm_financial_refund(c.tenant_id,rid);perform public.post_financial_refund(c.tenant_id,rid,'p8-ar-post-2');if(select amount_residual from public.account_move_lines where id=r.ar_source)<>8000 then raise exception'MULTIPLE_REFUND_RESIDUAL_INVALID';end if;
 begin perform public.create_financial_refund(c.tenant_id,r.ar_source,r.customer,10000,'EGP',r.destination,r.method,'Over refund','p8-over',r.branch);raise exception'OVER_REFUND_ACCEPTED';exception when insufficient_privilege or check_violation then null;end;
 begin perform public.create_financial_refund(c.tenant_id,r.ar_source,r.other_customer,1,'EGP',r.destination,r.method,'Cross partner','p8-cross-partner',r.branch);raise exception'CROSS_PARTNER_ACCEPTED';exception when check_violation then null;end;
 -- Customer advance 20 -> 15.
 x:=public.create_financial_refund(c.tenant_id,r.advance_source,r.customer,5000,'EGP',r.destination,r.method,'Advance return','p8-ca',r.branch);rid:=(x->>'refund_id')::uuid;perform public.submit_financial_refund(c.tenant_id,rid);perform public.confirm_financial_refund(c.tenant_id,rid);perform public.post_financial_refund(c.tenant_id,rid,'p8-ca-post');if(select amount_residual from public.account_move_lines where id=r.advance_source)<>15000 then raise exception'CUSTOMER_ADVANCE_REFUND_INVALID';end if;
 -- Applied advance exposes only residual 8: 10 rejected, 5 succeeds -> 3.
 begin perform public.create_financial_refund(c.tenant_id,r.applied_advance_source,r.customer,10000,'EGP',r.destination,r.method,'Applied over refund','p8-applied-over',r.branch);raise exception'APPLIED_PORTION_REFUNDED';exception when insufficient_privilege or check_violation then null;end;
 x:=public.create_financial_refund(c.tenant_id,r.applied_advance_source,r.customer,5000,'EGP',r.destination,r.method,'Unused advance refund','p8-applied-ok',r.branch);rid:=(x->>'refund_id')::uuid;perform public.submit_financial_refund(c.tenant_id,rid);perform public.confirm_financial_refund(c.tenant_id,rid);perform public.post_financial_refund(c.tenant_id,rid,'p8-applied-post');if(select amount_residual from public.account_move_lines where id=r.applied_advance_source)<>3000 then raise exception'UNUSED_ADVANCE_REFUND_INVALID';end if;
 -- Supplier advance and AP debit are inbound.
 foreach rid in array array[r.supplier_advance_source,r.ap_source]loop x:=public.create_financial_refund(c.tenant_id,rid,r.supplier,5000,'EGP',r.destination,r.method,'Supplier money return','p8-supplier-'||rid,r.branch);rid:=(x->>'refund_id')::uuid;perform public.submit_financial_refund(c.tenant_id,rid);perform public.confirm_financial_refund(c.tenant_id,rid);x:=public.post_financial_refund(c.tenant_id,rid,'p8-supplier-post-'||rid);mid:=(x->>'account_move_id')::uuid;if not exists(select 1 from public.account_move_lines where move_id=mid and account_id=r.cash and debit=5000)then raise exception'SUPPLIER_INBOUND_INVALID';end if;end loop;
 if(select status from public.financial_payments where id=r.original_payment)<>'confirmed'or exists(select 1 from public.financial_accounting_reversals where domain_type='payment'and domain_id=r.original_payment)then raise exception'REFUND_REVERSED_ORIGINAL_PAYMENT';end if;
 if(select coalesce(sum(debit-credit),0)from public.account_move_lines where account_id=r.cash)=cash0 then raise exception'REFUNDS_DID_NOT_MOVE_MONEY';end if;
end$$;set local role postgres;

-- Security/direct paths.
select set_config('request.jwt.claim.sub',other_auth::text,true)from phase8_context;set local role authenticated;
do $$declare c phase8_context%rowtype;r phase8_resources%rowtype;blocked boolean:=false;begin select*into c from phase8_context;select*into r from phase8_resources;begin perform public.create_financial_refund(c.tenant_id,r.ar_source,r.customer,1,'EGP',r.destination,r.method,'Unauthorized','p8-unauthorized',r.branch);exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception'UNAUTHORIZED_REFUND_ACCEPTED';end if;blocked:=false;begin insert into public.financial_refunds(tenant_id,refund_number,direction,amount,currency_code,partner_id,money_destination_id,payment_method_id,source_type,source_account_line_id,status,accounting_state,reason,created_by,idempotency_key,request_fingerprint)values(c.tenant_id,'RFD-2026-999999','outbound',1,'EGP',r.customer,r.destination,r.method,'customer_receivable_credit',r.ar_source,'draft','unposted','Forged',c.other_id,'forged',repeat('f',64));exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception'DIRECT_REFUND_INSERT_ACCEPTED';end if;blocked:=false;begin update public.financial_refunds set accounting_state='reversed'where tenant_id=c.tenant_id;exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception'DIRECT_REFUND_UPDATE_ACCEPTED';end if;end$$;set local role postgres;
do $$declare b phase8_before%rowtype;begin select*into b from phase8_before;if exists(select 1 from public.account_moves m join public.account_move_lines l on l.move_id=m.id and l.tenant_id=m.tenant_id where m.state='posted'group by m.id having round(sum(l.debit-l.credit),2)<>0)then raise exception'UNBALANCED_MOVE';end if;raise notice'PHASE8_BASELINE payments=% moves=% lines=% partials=% debit=% credit=%',b.payments,b.moves,b.lines,b.partials,b.debit,b.credit;end$$;
rollback;
