begin;
create temporary table crm_sale_context as select tenant_id,id tenant_user_id,auth_user_id from public.tenant_users where auth_user_id is not null and is_active limit 1;
grant select on crm_sale_context to authenticated;
select set_config('request.jwt.claim.sub',auth_user_id::text,true) from crm_sale_context;
set local role authenticated;
insert into public.crm_sales_users(tenant_id,user_id,active) select tenant_id,tenant_user_id,true from crm_sale_context on conflict(tenant_id,user_id) do update set active=true;
do $$
declare t uuid:=(select tenant_id from crm_sale_context);u uuid:=(select tenant_user_id from crm_sale_context);c uuid;a1 uuid;a2 uuid;a_bad uuid;l uuid;l_cash uuid;l_cancel uuid;s uuid;s2 uuid;s_cash uuid;j jsonb;
begin
 insert into public.crm_finance_companies(tenant_id,name,active,created_by) values(t,'شركة اختبار إتمام بيع',true,u) returning id into c;
 l:=(public.crm_create_lead(t,jsonb_build_object('customer_name','عميل إتمام بيع تقسيط','phone','01117777001','purchase_type','installment','assigned_sales_user_id',u,'next_followup_at',(now()+interval '1 day')::text))).id;
 a1:=(public.crm_create_installment_application(t,l,c,null,'موافقة أولى')).id;perform public.crm_transition_installment_application(t,a1,'approved','موافقة');
 a2:=(public.crm_create_installment_application(t,l,c,null,'موافقة ثانية بعد إغلاق الأولى')).id;perform public.crm_transition_installment_application(t,a2,'approved','موافقة');
 perform public.crm_select_installment_approval(t,a1);
 if not (select is_selected_approval from public.crm_installment_applications where id=a1) then raise exception 'first approval selection failed';end if;
 perform public.crm_select_installment_approval(t,a2);
 if (select count(*) from public.crm_installment_applications where lead_id=l and is_selected_approval)<>1 or not (select is_selected_approval from public.crm_installment_applications where id=a2) then raise exception 'approval replacement failed';end if;
 if not exists(select 1 from public.crm_installment_application_events where application_id=a2 and event_type='selected_for_sale') then raise exception 'selection event missing';end if;
 j:=public.crm_get_lead_sale_context(t,l);if (j->'selected_approval'->>'id')::uuid<>a2 then raise exception 'selected approval context failed';end if;
 a_bad:=(public.crm_create_installment_application(t,l,c,null,'غير معتمد')).id;
 begin perform public.crm_select_installment_approval(t,a_bad);raise exception 'non-approved selection allowed';exception when others then if sqlerrm='non-approved selection allowed' or position('CRM_INSTALLMENT_APPROVAL_REQUIRED' in sqlerrm)=0 then raise;end if;end;
 insert into public.showroom_sales(tenant_id,sale_number,sale_date,status,total_amount,created_by) values(t,'CRM-SALE-TEST-1',current_date,'confirmed',100000,u) returning id into s;
 perform public.crm_mark_lead_sold(t,l,s,a2);
 if not exists(select 1 from public.crm_leads where id=l and status='sold' and sale_id=s and sold_at is not null and sold_by=u and next_followup_at is null) then raise exception 'lead sold fields failed';end if;
 if not exists(select 1 from public.showroom_sales where id=s and crm_lead_id=l and crm_installment_application_id=a2) then raise exception 'bidirectional sale link failed';end if;
 if not exists(select 1 from public.crm_lead_activities where lead_id=l and activity_type='sold') then raise exception 'sold activity missing';end if;
 if not exists(select 1 from public.crm_installment_application_events where application_id=a2 and metadata->>'sale_id'=s::text) then raise exception 'application sale event missing';end if;
 j:=public.crm_list_lead_followups(t,u,'all','all','عميل إتمام بيع تقسيط','{}'::jsonb,date_trunc('day',now()),date_trunc('day',now())+interval '1 day',date_trunc('day',now())+interval '2 days',1,25);if (j->>'count')::int<>0 then raise exception 'sold lead remains in followups';end if;
 insert into public.showroom_sales(tenant_id,sale_number,sale_date,status,total_amount,created_by) values(t,'CRM-SALE-TEST-2',current_date,'confirmed',100000,u) returning id into s2;
 begin perform public.crm_mark_lead_sold(t,l,s2,a2);raise exception 'resale allowed';exception when others then if sqlerrm='resale allowed' or position('CRM_LEAD_ALREADY_SOLD' in sqlerrm)=0 then raise;end if;end;
 l_cash:=(public.crm_create_lead(t,jsonb_build_object('customer_name','عميل بيع كاش بعد رفض','phone','01117777002','purchase_type','installment','assigned_sales_user_id',u))).id;
 a_bad:=(public.crm_create_installment_application(t,l_cash,c,null,'رفض')).id;perform public.crm_transition_installment_application(t,a_bad,'rejected','مرفوض');
 insert into public.showroom_sales(tenant_id,sale_number,sale_date,status,total_amount,created_by) values(t,'CRM-CASH-TEST',current_date,'confirmed',50000,u) returning id into s_cash;
 perform public.crm_mark_lead_sold(t,l_cash,s_cash,null);
 if not exists(select 1 from public.showroom_sales where id=s_cash and crm_lead_id=l_cash and crm_installment_application_id is null) then raise exception 'cash sale after rejection failed';end if;
 l_cancel:=(public.crm_create_lead(t,jsonb_build_object('customer_name','عميل ملغي اختبار بيع','phone','01117777003','assigned_sales_user_id',u))).id;
 update public.crm_leads set status='cancelled' where id=l_cancel;
 begin perform public.crm_mark_lead_sold(t,l_cancel,s2,null);raise exception 'cancelled lead sold';exception when others then if sqlerrm='cancelled lead sold' or position('CRM_CANCELLED_LEAD_CANNOT_BE_SOLD' in sqlerrm)=0 then raise;end if;end;
 begin perform public.crm_mark_lead_sold(gen_random_uuid(),l,s,null);raise exception 'tenant isolation failed';exception when others then if sqlerrm='tenant isolation failed' or position('CRM_ACCESS_DENIED' in sqlerrm)=0 then raise;end if;end;
end $$;
rollback;
