begin;
create temporary table crm_finance_context as select tenant_id,id tenant_user_id,auth_user_id from public.tenant_users where auth_user_id is not null and is_active limit 1;
grant select on crm_finance_context to authenticated;
select set_config('request.jwt.claim.sub',auth_user_id::text,true) from crm_finance_context;
set local role authenticated;
insert into public.crm_sales_users(tenant_id,user_id,active) select tenant_id,tenant_user_id,true from crm_finance_context on conflict(tenant_id,user_id) do update set active=true;
do $$
declare t uuid:=(select tenant_id from crm_finance_context);u uuid:=(select tenant_user_id from crm_finance_context);c1 uuid;c2 uuid;r1 uuid;r2 uuid;r3 uuid;l1 uuid;l2 uuid;a1 uuid;j jsonb;
begin
 insert into public.crm_finance_companies(tenant_id,name,code,phone,active,created_by) values(t,'شركة دليل اختبار','FD-TEST','01000000000',true,u) returning id into c1;
 begin insert into public.crm_finance_companies(tenant_id,name,active,created_by) values(t,'شركة دليل اختبار',true,u);raise exception 'duplicate name allowed';exception when unique_violation then null;end;
 begin insert into public.crm_finance_companies(tenant_id,name,code,active,created_by) values(t,'شركة دليل اختبار أخرى','FD-TEST',true,u);raise exception 'duplicate code allowed';exception when unique_violation then null;end;
 update public.crm_finance_companies set phone='01111111111',notes='تم التعديل',active=false where id=c1;
 if not exists(select 1 from public.crm_finance_companies where id=c1 and phone='01111111111' and not active) then raise exception 'company update/deactivate failed';end if;
 update public.crm_finance_companies set active=true where id=c1;
 insert into public.crm_finance_companies(tenant_id,name,active,created_by) values(t,'شركة دليل اختبار ثانية',true,u) returning id into c2;
 r1:=(public.crm_create_finance_representative(t,jsonb_build_object('finance_company_id',c1,'name','مندوب دليل أول','phone','01010000001','is_primary',true,'active',true))).id;
 r2:=(public.crm_create_finance_representative(t,jsonb_build_object('finance_company_id',c1,'name','مندوب دليل ثان','is_primary',true,'active',true))).id;
 if (select count(*) from public.crm_finance_company_representatives where finance_company_id=c1 and active and is_primary)<>1 or not (select is_primary from public.crm_finance_company_representatives where id=r2) then raise exception 'atomic primary replacement failed';end if;
 perform public.crm_set_primary_finance_representative(t,r1);
 if not (select is_primary from public.crm_finance_company_representatives where id=r1) or (select is_primary from public.crm_finance_company_representatives where id=r2) then raise exception 'set primary failed';end if;
 perform public.crm_set_finance_representative_active(t,r1,false);
 if (select active or is_primary from public.crm_finance_company_representatives where id=r1) then raise exception 'primary deactivate failed';end if;
 perform public.crm_set_finance_representative_active(t,r1,true);
 perform public.crm_update_finance_representative(t,r1,jsonb_build_object('finance_company_id',c1,'name','مندوب دليل أول معدل','job_title','مدير','is_primary',false,'active',true));
 if not exists(select 1 from public.crm_finance_company_representatives where id=r1 and name='مندوب دليل أول معدل' and job_title='مدير') then raise exception 'representative update failed';end if;
 update public.crm_finance_companies set active=false where id=c2;
 begin perform public.crm_create_finance_representative(t,jsonb_build_object('finance_company_id',c2,'name','مندوب مرفوض'));raise exception 'inactive company representative allowed';exception when others then if sqlerrm='inactive company representative allowed' or position('CRM_FINANCE_COMPANY_INACTIVE' in sqlerrm)=0 then raise;end if;end;
 begin perform public.crm_create_finance_representative(t,jsonb_build_object('finance_company_id',gen_random_uuid(),'name','مندوب Tenant آخر'));raise exception 'foreign company representative allowed';exception when others then if sqlerrm='foreign company representative allowed' or position('CRM_FINANCE_COMPANY_INACTIVE' in sqlerrm)=0 then raise;end if;end;
 update public.crm_finance_companies set active=true where id=c2;
 r3:=(public.crm_create_finance_representative(t,jsonb_build_object('finance_company_id',c2,'name','مندوب شركة ثانية','active',true))).id;
 l1:=(public.crm_create_lead(t,jsonb_build_object('customer_name','عميل دليل تمويل اختبار','phone','01118888001','assigned_sales_user_id',u))).id;
 l2:=(public.crm_create_lead(t,jsonb_build_object('customer_name','عميل دليل تمويل ثان','phone','01118888002','assigned_sales_user_id',u))).id;
 a1:=(public.crm_create_installment_application(t,l1,c1,r1,'اختبار العرض القديم')).id;
 begin perform public.crm_create_installment_application(t,l2,c1,r3,null);raise exception 'mismatched representative allowed';exception when others then if sqlerrm='mismatched representative allowed' or position('CRM_INVALID_FINANCE_REPRESENTATIVE' in sqlerrm)=0 then raise;end if;end;
 perform public.crm_set_finance_representative_active(t,r1,false);
 begin perform public.crm_create_installment_application(t,l2,c1,r1,null);raise exception 'inactive representative allowed';exception when others then if sqlerrm='inactive representative allowed' or position('CRM_INVALID_FINANCE_REPRESENTATIVE' in sqlerrm)=0 then raise;end if;end;
 update public.crm_finance_companies set active=false where id=c1;
 begin perform public.crm_create_installment_application(t,l2,c1,null,null);raise exception 'inactive company application allowed';exception when others then if sqlerrm='inactive company application allowed' or position('CRM_FINANCE_COMPANY_NOT_FOUND' in sqlerrm)=0 then raise;end if;end;
 j:=public.crm_list_installment_applications(t,'عميل دليل','{}'::jsonb,l1,1,25);
 if (j->>'count')::int<>1 or j->'data'->0->>'company_name'<>'شركة دليل اختبار' or (j->'data'->0->>'company_active')::boolean or (j->'data'->0->>'representative_active')::boolean then raise exception 'historic application visibility failed';end if;
 begin perform public.crm_set_primary_finance_representative(gen_random_uuid(),r2);raise exception 'tenant isolation failed';exception when others then if sqlerrm='tenant isolation failed' or position('CRM_ACCESS_DENIED' in sqlerrm)=0 then raise;end if;end;
end $$;
rollback;
