begin;
create temporary table crm_lifecycle_context as select tenant_id,id tenant_user_id,auth_user_id from public.tenant_users where auth_user_id is not null and is_active limit 1;
grant select on crm_lifecycle_context to authenticated;
create temporary table crm_foreign_reason as with x as(insert into public.crm_lead_cancel_reasons(tenant_id,name) values(gen_random_uuid(),'سبب Tenant آخر') returning id)select id from x;
create temporary table crm_foreign_lead as with x as(insert into public.crm_leads(tenant_id,customer_name,phone) values(gen_random_uuid(),'Lead Tenant آخر','09999999998') returning id)select id from x;
grant select on crm_foreign_reason,crm_foreign_lead to authenticated;
select set_config('request.jwt.claim.sub',auth_user_id::text,true) from crm_lifecycle_context;set local role authenticated;
insert into public.crm_sales_users(tenant_id,user_id,active)select tenant_id,tenant_user_id,true from crm_lifecycle_context on conflict(tenant_id,user_id)do update set active=true;
create temporary table crm_lifecycle_data(kind text,id uuid);grant select,insert on crm_lifecycle_data to authenticated;
with x as(insert into public.crm_lead_cancel_reasons(tenant_id,name,active,created_by)select tenant_id,'سبب اختبار فعال',true,tenant_user_id from crm_lifecycle_context returning id)insert into crm_lifecycle_data select 'reason',id from x;
with x as(insert into public.crm_lead_cancel_reasons(tenant_id,name,active,created_by)select tenant_id,'سبب اختبار غير فعال',false,tenant_user_id from crm_lifecycle_context returning id)insert into crm_lifecycle_data select 'inactive_reason',id from x;
insert into crm_lifecycle_data select 'assigned',(public.crm_create_lead((select tenant_id from crm_lifecycle_context),jsonb_build_object('customer_name','اختبار إلغاء موزع','phone','01000000101','assigned_sales_user_id',(select tenant_user_id from crm_lifecycle_context),'next_followup_at',(now()+interval '1 day')::text))).id;
insert into crm_lifecycle_data select 'unassigned',(public.crm_create_lead((select tenant_id from crm_lifecycle_context),jsonb_build_object('customer_name','اختبار إلغاء غير موزع','phone','01000000102'))).id;
insert into crm_lifecycle_data select 'sold',(public.crm_create_lead((select tenant_id from crm_lifecycle_context),jsonb_build_object('customer_name','اختبار مباع','phone','01000000103'))).id;
update public.crm_leads set status='sold' where id=(select id from crm_lifecycle_data where kind='sold');
do $$ declare t uuid:=(select tenant_id from crm_lifecycle_context);r uuid:=(select id from crm_lifecycle_data where kind='reason');a uuid:=(select id from crm_lifecycle_data where kind='assigned');u uuid:=(select id from crm_lifecycle_data where kind='unassigned');s uuid:=(select id from crm_lifecycle_data where kind='sold');sales uuid:=(select tenant_user_id from crm_lifecycle_context);begin
 begin perform public.crm_cancel_lead(t,u,null,null);raise exception 'missing reason accepted';exception when others then if sqlerrm='missing reason accepted'then raise;end if;end;
 begin perform public.crm_cancel_lead(t,u,(select id from crm_lifecycle_data where kind='inactive_reason'),null);raise exception 'inactive reason accepted';exception when others then if sqlerrm='inactive reason accepted'then raise;end if;end;
 begin perform public.crm_cancel_lead(t,u,(select id from crm_foreign_reason),null);raise exception 'foreign reason accepted';exception when others then if sqlerrm='foreign reason accepted'then raise;end if;end;
 begin perform public.crm_cancel_lead(t,s,r,null);raise exception 'sold accepted';exception when others then if sqlerrm='sold accepted'then raise;end if;end;
 perform public.crm_cancel_lead(t,a,r,'ملاحظة إلغاء');
 if not exists(select 1 from public.crm_leads where id=a and status='cancelled' and cancel_reason_id=r and cancel_notes='ملاحظة إلغاء' and cancelled_at is not null and cancelled_by is not null and next_followup_at is null and assigned_sales_user_id=sales)then raise exception 'cancel fields failed';end if;
 if not exists(select 1 from public.crm_lead_activities where lead_id=a and activity_type='cancelled')then raise exception 'cancel activity missing';end if;
 begin perform public.crm_cancel_lead(t,a,r,null);raise exception 'duplicate cancel accepted';exception when others then if sqlerrm='duplicate cancel accepted'then raise;end if;end;
 perform public.crm_reopen_lead(t,a,'إعادة فتح موزع',now()+interval '2 days');
 if not exists(select 1 from public.crm_leads where id=a and status='in_followup' and cancel_reason_id is null and cancel_notes is null and cancelled_at is null and cancelled_by is null and next_followup_at is not null)then raise exception 'assigned reopen failed';end if;
 if not exists(select 1 from public.crm_lead_activities where lead_id=a and activity_type='reopened')then raise exception 'reopen activity missing';end if;
 perform public.crm_cancel_lead(t,u,r,null);perform public.crm_reopen_lead(t,u,'إعادة فتح غير موزع',null);
 if not exists(select 1 from public.crm_leads where id=u and status='new')then raise exception 'unassigned reopen failed';end if;
 begin perform public.crm_reopen_lead(t,u,'مرة أخرى',null);raise exception 'noncancelled reopen accepted';exception when others then if sqlerrm='noncancelled reopen accepted'then raise;end if;end;
 begin perform public.crm_cancel_lead(t,(select id from crm_foreign_lead),r,null);raise exception 'cross tenant accepted';exception when others then if sqlerrm='cross tenant accepted'then raise;end if;end;
end $$;
rollback;
