import { useEffect, useState } from 'react';
import { Plus, X } from 'lucide-react';
import { Button } from '@/core/ui/button';
import { Input } from '@/core/ui/input';
import { Sheet, SheetBody, SheetContent, SheetDescription, SheetDismissButton, SheetFooter, SheetHeader, SheetTitle } from '@/core/ui/sheet';
import { useUserAccess } from '../hooks/useAccessControl';
import { accessControlService } from '../services/accessControl.service';
import { DetailSkeleton, EmptyBlock, LoadError, SectionTabs, StatusText } from '../shared/AccessControlPrimitives';
import { friendlyAccessError, memberName, validateDefaults } from '../utils/accessControl';

const tabs=[{value:'overview',label:'نظرة عامة'},{value:'roles',label:'الأدوار'},{value:'scope',label:'نطاق العمل'}];
const sortIds=value=>[...value].sort();
const snapshot=d=>({roleIds:sortIds(d.memberships.map(x=>x.group_id)),branchIds:sortIds(d.branchAccess.map(x=>x.branchId)),posIds:sortIds(d.posAccess.map(x=>x.posId)),stockIds:sortIds(d.stockAccess.map(x=>x.stockLocationId)),accountIds:sortIds(d.accountAccess.map(x=>x.accountId)),defaults:d.defaults});
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);

export function UserDetails({ tenantId, user, onClose, onChanged, onOpenRole }) {
  const access=useUserAccess(tenantId,user); const d=access.data; const owner=user?.role==='owner';
  const [tab,setTab]=useState('overview'); const [draft,setDraft]=useState(null); const [initial,setInitial]=useState(null); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
  useEffect(()=>{setTab('overview');setDraft(null);setInitial(null);setError('')},[user?.id]);
  useEffect(()=>{if(d){const next=snapshot(d);setDraft(next);setInitial(next)}},[d]);
  const dirty=Boolean(draft&&initial&&!same(draft,initial));
  const reset=()=>{setDraft(initial);setError('')};
  const save=async()=>{if(!dirty||saving)return;const defaultsError=owner?'':validateDefaults(draftToDefaults(draft),draftDetails(d,draft));if(defaultsError){setError(defaultsError);return}setSaving(true);setError('');try{await accessControlService.saveUserAccessPlan({tenantId,userId:user.id,original:initial,next:{...draft,posBranchById:Object.fromEntries(d.poses.map(x=>[x.id,x.branch_id])),stockBranchById:Object.fromEntries(d.stocks.map(x=>[x.id,x.branch_id]))},owner});await access.reload();await onChanged?.()}catch(e){setError(friendlyAccessError(e))}finally{setSaving(false)}};
  return <Sheet open={Boolean(user)} onOpenChange={open=>!open&&onClose()}><SheetContent side="left" className="w-full max-w-none sm:max-w-3xl" dir="rtl"><SheetDismissButton aria-label="إغلاق تفاصيل المستخدم"/><SheetHeader><SheetTitle>{memberName(user)}</SheetTitle><SheetDescription>{owner?'مالك الشركة · وصول كامل تلقائيًا':'راجع أدوار المستخدم وحدد الأماكن والموارد التي يستطيع العمل عليها.'}</SheetDescription><div className="overflow-x-auto pt-3"><SectionTabs value={tab} onChange={setTab} items={owner?tabs.filter(x=>x.value!=='roles'):tabs} label="أقسام تفاصيل المستخدم"/></div></SheetHeader><SheetBody className="bg-white">{access.status==='loading'?<DetailSkeleton/>:null}{access.error?<LoadError message={access.error} onRetry={access.reload}/>:null}{d&&draft?<>{tab==='overview'?<Overview user={user} data={d} owner={owner} onOpenRole={onOpenRole}/>:null}{tab==='roles'&&!owner?<UserRoles data={d} draft={draft} setDraft={setDraft} onOpenRole={onOpenRole}/>:null}{tab==='scope'?<UserScope data={d} draft={draft} setDraft={setDraft} owner={owner} tenantId={tenantId}/>:null}</>:null}{error?<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>:null}</SheetBody><SheetFooter><Button variant="secondary" disabled={!dirty||saving} onClick={reset}>إلغاء التغييرات</Button><Button disabled={!dirty||saving} onClick={save}>{saving?'جاري الحفظ...':'حفظ التغييرات'}</Button></SheetFooter></SheetContent></Sheet>;
}

function Overview({user,data,owner,onOpenRole}) {const roles=data.groups.filter(g=>data.memberships.some(m=>m.group_id===g.id));const apps=data.installedApps.filter(app=>owner||app.hasAccess);const branch=data.branches.find(x=>x.id===data.defaults.defaultBranchId);return <div className="space-y-8"><section><p className="text-xs font-black text-slate-400">المستخدم</p><div className="mt-3 flex flex-wrap items-center gap-x-5 gap-y-2"><h3 className="text-lg font-black">{memberName(user)}</h3><StatusText active={user.isActive}/><span className="text-sm text-slate-500">{[user.email,user.phone].filter(Boolean).join(' · ')||'لا توجد بيانات اتصال'}</span></div>{owner?<p className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">مالك الشركة — وصول كامل تلقائيًا إلى التطبيقات والموارد.</p>:null}</section>{!owner?<Summary title="الأدوار الحالية" value={roles.length?roles.map(role=><button key={role.id} className="font-bold text-blue-700 hover:underline" onClick={()=>onOpenRole(role)}>{role.name}</button>):'لا توجد أدوار مسندة لهذا المستخدم.'} meta={`${roles.length} دور`}/>:null}<Summary title="التطبيقات المتاحة" value={apps.length?apps.map(x=>x.name).join(' · '):'لا توجد تطبيقات متاحة حاليًا.'} meta={`${apps.length} تطبيق`}/><Summary title="النطاق" value={branch?`الفرع الافتراضي: ${branch.name}`:'لم يُحدد فرع افتراضي.'} meta={`${data.branchAccess.length} فرع · ${data.posAccess.length} نقطة بيع · ${data.stockAccess.length} موقع مخزون`}/></div>}
function Summary({title,value,meta}){return <section className="border-t border-slate-100 pt-5"><div className="flex items-center justify-between"><h3 className="font-black">{title}</h3><span className="text-xs text-slate-400">{meta}</span></div><div className="mt-2 flex flex-wrap gap-2 text-sm leading-7 text-slate-600">{value}</div></section>}

function UserRoles({data,draft,setDraft,onOpenRole}) {const [adding,setAdding]=useState(false);const [term,setTerm]=useState('');const selected=new Set(draft.roleIds);const current=data.groups.filter(g=>selected.has(g.id));const available=data.groups.filter(g=>!selected.has(g.id)&&(!term||[g.name,g.description,g.code].some(v=>v?.toLowerCase().includes(term.toLowerCase()))));const remove=id=>setDraft(x=>({...x,roleIds:x.roleIds.filter(value=>value!==id)}));return <div className="space-y-5"><div><h3 className="text-lg font-black">الأدوار الحالية</h3><p className="mt-1 text-sm text-slate-500">الأدوار تجمع صلاحيات التطبيقات، ويمكن حفظ كل التغييرات معًا.</p></div>{current.length?<div className="divide-y divide-slate-100 rounded-2xl border border-slate-200">{current.map(role=><div key={role.id} className="flex items-center gap-3 px-4 py-3"><button className="min-w-0 flex-1 text-right" onClick={()=>onOpenRole(role)}><p className="font-bold">{role.name}</p><p className="truncate text-xs text-slate-500">{role.description||'لا يوجد وصف'}</p></button><button aria-label={`إزالة دور ${role.name}`} className="rounded-full p-2 text-slate-400 hover:bg-red-50 hover:text-red-600" onClick={()=>remove(role.id)}><X className="h-4 w-4"/></button></div>)}</div>:<EmptyBlock title="لا توجد أدوار مسندة لهذا المستخدم." description={data.groups.length?'يمكنك إضافة دور من الأدوار المتاحة.':'أنشئ دورًا أولًا من قسم الأدوار.'}/>}<Button variant="secondary" onClick={()=>setAdding(x=>!x)}><Plus className="h-4 w-4"/>إضافة دور</Button>{adding?<div className="rounded-2xl bg-slate-50 p-4"><label className="text-sm font-bold">البحث في الأدوار<Input className="mt-2" value={term} onChange={e=>setTerm(e.target.value)} placeholder="اسم الدور..."/></label><div className="mt-3 space-y-1">{available.map(role=><button key={role.id} className="flex w-full items-center justify-between rounded-xl bg-white px-3 py-3 text-right hover:bg-blue-50" onClick={()=>setDraft(x=>({...x,roleIds:[...x.roleIds,role.id]}))}><span><span className="block text-sm font-bold">{role.name}</span><span className="text-xs text-slate-500">{role.description}</span></span><Plus className="h-4 w-4"/></button>)}{!available.length?<p className="py-4 text-center text-sm text-slate-500">لا توجد أدوار متاحة.</p>:null}</div></div>:null}</div>}

function UserScope({data,draft,setDraft,owner,tenantId}) {const branches=new Set(draft.branchIds);const setIds=(key,ids)=>setDraft(x=>({...x,[key]:sortIds(ids)}));const toggle=(key,id)=>{const values=new Set(draft[key]);values.has(id)?values.delete(id):values.add(id);setIds(key,values)};const branchItems=data.branches.filter(b=>branches.has(b.id));return <div className="space-y-8"><div><h3 className="text-lg font-black">نطاق العمل</h3><p className="mt-1 text-sm text-slate-500">حدد الأماكن والموارد التي يستطيع المستخدم العمل عليها.</p></div>{owner?<p className="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">نطاق المالك شامل تلقائيًا. يمكن تعديل الإعدادات الافتراضية فقط.</p>:<><Picker title="الفروع" items={data.branches} selected={branches} onToggle={id=>{const next=new Set(draft.branchIds);if(next.has(id)){next.delete(id);setDraft(x=>({...x,branchIds:sortIds(next),posIds:x.posIds.filter(posId=>data.poses.find(p=>p.id===posId)?.branch_id!==id),stockIds:x.stockIds.filter(stockId=>data.stocks.find(s=>s.id===stockId)?.branch_id!==id)}))}else toggle('branchIds',id)}} empty="لا توجد فروع مسموحة. أضف فرعًا إلى نطاق المستخدم."/>{branchItems.length?branchItems.map(branch=><section key={branch.id} className="border-t border-slate-100 pt-5"><h4 className="font-black">{branch.name}</h4><div className="mt-4 grid gap-5 md:grid-cols-2"><Picker title="نقاط البيع" compact items={data.poses.filter(x=>x.branch_id===branch.id)} selected={new Set(draft.posIds)} onToggle={id=>toggle('posIds',id)} empty="لا توجد نقاط بيع متاحة لهذا الفرع."/><Picker title="مواقع المخزون" compact items={data.stocks.filter(x=>x.branch_id===branch.id)} selected={new Set(draft.stockIds)} onToggle={id=>toggle('stockIds',id)} empty="لا توجد مواقع مخزون متاحة لهذا الفرع."/></div></section>):<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">اختر فرعًا أولًا لإتاحة نقاط البيع ومواقع المخزون.</p>}<AccountPicker tenantId={tenantId} selected={new Set(draft.accountIds)} setSelected={ids=>setIds('accountIds',ids)}/></>}<Defaults data={data} draft={draft} setDraft={setDraft} owner={owner}/></div>}

function Picker({title,items,selected,onToggle,empty,compact=false}){const [open,setOpen]=useState(false);const chosen=items.filter(x=>selected.has(x.id));return <section><div className="flex items-center justify-between"><div><h4 className={compact?'text-sm font-black':'font-black'}>{title}</h4><p className="mt-1 text-xs text-slate-400">{chosen.length} محدد</p></div><Button size="sm" variant="secondary" onClick={()=>setOpen(x=>!x)}>{open?'إغلاق':`إدارة ${title}`}</Button></div>{chosen.length?<div className="mt-3 flex flex-wrap gap-2">{chosen.map(x=><button key={x.id} onClick={()=>onToggle(x.id)} className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold">{x.name}<X className="h-3 w-3"/></button>)}</div>:<p className="mt-3 text-sm text-slate-500">{empty}</p>}{open?<div className="mt-3 max-h-56 space-y-1 overflow-y-auto rounded-xl bg-slate-50 p-2">{items.map(x=><label key={x.id} className="flex cursor-pointer items-center gap-3 rounded-lg bg-white px-3 py-2 text-sm font-bold"><input type="checkbox" checked={selected.has(x.id)} onChange={()=>onToggle(x.id)}/>{x.name}</label>)}{!items.length?<p className="p-3 text-center text-sm text-slate-500">لا توجد عناصر متاحة.</p>:null}</div>:null}</section>}

function AccountPicker({tenantId,selected,setSelected}){const [open,setOpen]=useState(false);const [term,setTerm]=useState('');const [page,setPage]=useState(0);const [state,setState]=useState({loading:false,items:[],count:0,error:''});useEffect(()=>{if(!open)return;let live=true;const timer=setTimeout(async()=>{setState(x=>({...x,loading:true,error:''}));try{const result=await accessControlService.searchAccounts({tenantId,term,page});if(live)setState({loading:false,error:'',...result})}catch{if(live)setState({loading:false,items:[],count:0,error:'تعذر تحميل الحسابات.'})}},250);return()=>{live=false;clearTimeout(timer)}},[open,page,tenantId,term]);const toggle=id=>{const next=new Set(selected);next.has(id)?next.delete(id):next.add(id);setSelected(next)};return <section className="border-t border-slate-100 pt-5"><div className="flex items-center justify-between"><div><h4 className="font-black">الحسابات المسموحة</h4><p className="mt-1 text-sm text-slate-500">{selected.size} حساب</p></div><Button size="sm" variant="secondary" onClick={()=>setOpen(x=>!x)}>{open?'إغلاق':'إدارة الحسابات'}</Button></div>{open?<div className="mt-4 rounded-2xl bg-slate-50 p-4"><label className="text-sm font-bold">بحث بالكود أو اسم الحساب<Input className="mt-2" value={term} onChange={e=>{setTerm(e.target.value);setPage(0)}}/></label>{state.loading?<div className="mt-3 h-28 animate-pulse rounded-xl bg-slate-100"/>:null}{state.error?<p className="mt-3 text-sm text-red-700">{state.error}</p>:null}{!state.loading?<div className="mt-3 space-y-1">{state.items.map(a=><label key={a.id} className="flex cursor-pointer gap-3 rounded-lg bg-white p-3 text-sm"><input type="checkbox" checked={selected.has(a.id)} onChange={()=>toggle(a.id)}/><span><b>{a.code||'—'} — {a.name}</b><span className="block text-xs text-slate-400">{a.account_type}</span></span></label>)}</div>:null}<div className="mt-3 flex items-center justify-between"><Button size="sm" variant="secondary" disabled={!page||state.loading} onClick={()=>setPage(x=>x-1)}>السابق</Button><span className="text-xs text-slate-500">{state.count} حساب</span><Button size="sm" variant="secondary" disabled={(page+1)*25>=state.count||state.loading} onClick={()=>setPage(x=>x+1)}>التالي</Button></div></div>:null}</section>}

function Defaults({data,draft,setDraft,owner}){const allowedBranches=owner?data.branches:data.branches.filter(x=>draft.branchIds.includes(x.id));const allowedPos=data.poses.filter(x=>(owner||draft.posIds.includes(x.id))&&x.branch_id===draft.defaults.defaultBranchId);const allowedStocks=data.stocks.filter(x=>(owner||draft.stockIds.includes(x.id))&&x.branch_id===draft.defaults.defaultBranchId);const update=(key,value)=>setDraft(x=>({...x,defaults:{...x.defaults,[key]:value,...(key==='defaultBranchId'?{defaultPosId:'',defaultStockLocationId:''}:{})}}));return <section className="border-t border-slate-100 pt-5"><h4 className="font-black">الإعدادات الافتراضية</h4><div className="mt-4 grid gap-4 md:grid-cols-3"><Select label="الفرع الافتراضي" items={allowedBranches} value={draft.defaults.defaultBranchId} onChange={v=>update('defaultBranchId',v)}/><Select label="نقطة البيع الافتراضية" items={allowedPos} value={draft.defaults.defaultPosId} onChange={v=>update('defaultPosId',v)}/><Select label="موقع المخزون الافتراضي" items={allowedStocks} value={draft.defaults.defaultStockLocationId} onChange={v=>update('defaultStockLocationId',v)}/></div></section>}
function Select({label,items,value,onChange}){return <label className="text-sm font-bold">{label}<select className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3" value={value} onChange={e=>onChange(e.target.value)}><option value="">بدون اختيار</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
function draftToDefaults(draft){return {defaultBranchId:draft.defaults.defaultBranchId,defaultPosId:draft.defaults.defaultPosId,defaultStockLocationId:draft.defaults.defaultStockLocationId}}
function draftDetails(data,draft){return {...data,branchAccess:draft.branchIds.map(branchId=>({branchId})),posAccess:draft.posIds.map(posId=>({posId,branchId:data.poses.find(x=>x.id===posId)?.branch_id})),stockAccess:draft.stockIds.map(stockLocationId=>({stockLocationId,branchId:data.stocks.find(x=>x.id===stockLocationId)?.branch_id}))}}
