import { Search, Users } from 'lucide-react';
import { Input } from '@/core/ui/input';
import { Button } from '@/core/ui/button';
import { DetailSkeleton, EmptyBlock, LoadError, StatusText } from '../shared/AccessControlPrimitives';
import { memberName } from '../utils/accessControl';

export function UsersList({ users, term, onTermChange, statusFilter, onStatusFilterChange, onSelect }) {
  const query=term.trim().toLowerCase();
  const items=users.items.filter(user=>(statusFilter==='all'||String(user.isActive)===statusFilter)&&(!query||[user.fullName,user.email,user.phone].some(value=>value?.toLowerCase().includes(query))));
  return <div className="space-y-4"><div className="flex flex-col gap-2 sm:flex-row"><label className="relative flex-1"><span className="sr-only">بحث في المستخدمين</span><Search className="absolute right-4 top-3.5 h-4 w-4 text-slate-400"/><Input className="pr-11" value={term} onChange={e=>onTermChange(e.target.value)} placeholder="بحث بالاسم أو البريد أو الهاتف..."/></label><label><span className="sr-only">حالة المستخدم</span><select className="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold sm:w-40" value={statusFilter} onChange={e=>onStatusFilterChange(e.target.value)}><option value="all">كل الحالات</option><option value="true">نشط</option><option value="false">غير نشط</option></select></label></div>{users.status==='loading'?<DetailSkeleton/>:null}{users.error?<LoadError message={users.error} onRetry={users.reload}/>:null}{users.status==='ready'&&!items.length?<EmptyBlock title="لا يوجد مستخدمون مطابقون" description="جرّب تغيير البحث أو فلتر الحالة."/>:null}{items.length?<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white">{items.map((user,index)=><button key={user.id} type="button" onClick={()=>onSelect(user)} className={`grid w-full gap-3 px-4 py-4 text-right transition hover:bg-slate-50 sm:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)_auto] sm:items-center ${index?'border-t border-slate-100':''}`}><div className="min-w-0"><p className="truncate font-black text-slate-900">{memberName(user)}</p><p className="mt-1 truncate text-xs text-slate-500">{user.email||user.phone||'لا توجد بيانات اتصال'}</p></div><div className="min-w-0"><p className="text-xs font-bold text-slate-400">الأدوار</p><p className="mt-1 truncate text-sm text-slate-700">{user.groupNames?.length?user.groupNames.join(' · '):'لا توجد أدوار'}</p></div><div className="flex items-center justify-between gap-4 sm:block sm:text-left"><StatusText active={user.isActive}/>{user.defaultBranchName?<p className="mt-2 text-xs text-slate-500">{user.defaultBranchName}</p>:null}</div></button>)}</div>:null}</div>;
}
