import { useMemo, useState } from 'react';
import { KeyRound } from 'lucide-react';
import { Input } from '@/core/ui/input'; import { LoadingSpinner } from '@/core/ui/loading-spinner';
import { usePermissionCatalog } from '../hooks/useAccessControl'; import { buildPermissionCatalogView, catalogStats } from '../utils/permissionCatalogView';
import { PermissionCatalogSection } from './PermissionCatalogSection'; import { PermissionDetailsDrawer } from './PermissionDetailsDrawer';

export function PermissionCatalog({active}) {
  const catalog=usePermissionCatalog(active);const [term,setTerm]=useState('');const [moduleFilter,setModuleFilter]=useState('all');const [typeFilter,setTypeFilter]=useState('all');const [selected,setSelected]=useState(null);
  const sections=useMemo(()=>buildPermissionCatalogView({permissions:catalog.data?.permissions,modules:catalog.data?.modules,term,moduleFilter,typeFilter}),[catalog.data,moduleFilter,term,typeFilter]); const stats=catalog.data?catalogStats(catalog.data.permissions,catalog.data.modules):null; const moduleName=new Map(catalog.data?.modules.map(module=>[module.technical_name,module.name])||[]).get(selected?.module_code)||(selected?'غير مصنفة / تحتاج مراجعة':'');
  if(catalog.status==='loading')return <LoadingSpinner title="جاري تحميل دليل الصلاحيات"/>;
  if(catalog.error)return <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{catalog.error}</div>;
  if(catalog.status==='ready'&&!catalog.data?.permissions.length)return <div className="rounded-xl border bg-white p-10 text-center"><KeyRound className="mx-auto h-9 w-9 text-slate-400"/><p className="mt-3 font-black">لا توجد صلاحيات نشطة.</p></div>;
  if(!catalog.data)return null;
  return <div className="space-y-4"><div className="grid grid-cols-2 gap-2 lg:grid-cols-5"><Stat label="إجمالي الصلاحيات" value={stats.total}/><Stat label="وصول للتطبيقات" value={stats.appAccess}/><Stat label="العمليات" value={stats.actions}/><Stat label="التطبيقات" value={stats.apps}/><Stat label="تحتاج مراجعة" value={stats.unclassified}/></div><div className="grid gap-2 md:grid-cols-3"><Input value={term} onChange={e=>setTerm(e.target.value)} placeholder="بحث بالاسم أو الوصف أو الكود..."/><select className="h-11 rounded-xl border bg-white px-3" value={moduleFilter} onChange={e=>setModuleFilter(e.target.value)}><option value="all">كل التطبيقات</option>{groupPermissionOptions(catalog.data.permissions,catalog.data.modules).map(option=><option key={option.code} value={option.code}>{option.name}</option>)}</select><select className="h-11 rounded-xl border bg-white px-3" value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="all">كل الأنواع</option><option value="app_access">الوصول للتطبيقات</option><option value="action">العمليات</option></select></div>{sections.length?<div className="grid gap-3 lg:grid-cols-2">{sections.map(section=><PermissionCatalogSection key={section.code} section={section} usage={catalog.data.usage} onSelect={setSelected}/>)}</div>:<div className="rounded-xl border bg-white p-10 text-center text-sm text-slate-500">لا توجد نتائج مطابقة.</div>}<PermissionDetailsDrawer permission={selected} moduleName={moduleName} usage={selected?catalog.data.usage.get(selected.id):null} onClose={()=>setSelected(null)}/></div>;
}
function Stat({label,value}){return <div className="rounded-xl border bg-white p-3"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>}
function groupPermissionOptions(permissions,modules){const known=new Map(modules.map(m=>[m.technical_name,m.name]));const codes=new Set(permissions.map(p=>known.has(p.module_code)?p.module_code:'__unclassified'));return [...codes].map(code=>({code,name:code==='__unclassified'?'غير مصنفة / تحتاج مراجعة':known.get(code)})).sort((a,b)=>a.name.localeCompare(b.name,'ar'))}
