import { useEffect, useMemo, useState } from 'react';
import { Badge } from '@/core/ui/badge'; import { Button } from '@/core/ui/button';
import { Sheet,SheetBody,SheetContent,SheetDescription,SheetDismissButton,SheetHeader,SheetTitle } from '@/core/ui/sheet';
import { accessControlService } from '../services/accessControl.service'; import { useUserAccess } from '../hooks/useAccessControl';
import { memberName, roleLabel, validateDefaults } from '../utils/accessControl'; import { AccessCheck, AccessSection } from './AccessSection'; import { AccountsAccess } from './AccountsAccess';

export function UserAccessDrawer({tenantId,user,onClose,onChanged}) {
 const access=useUserAccess(tenantId,user); const d=access.data; const owner=user?.role==='owner';
 const [defaults,setDefaults]=useState(null); useEffect(()=>setDefaults(d?.defaults||null),[d]);
 const branchIds=useMemo(()=>new Set(d?.branchAccess.map(x=>x.branchId)||[]),[d]); const posIds=new Set(d?.posAccess.map(x=>x.posId)||[]); const stockIds=new Set(d?.stockAccess.map(x=>x.stockLocationId)||[]); const groupIds=new Set(d?.memberships.map(x=>x.group_id)||[]);
 const grouped=(items)=>d?.branches.filter(b=>branchIds.has(b.id)).map(b=>({branch:b,items:items.filter(x=>x.branch_id===b.id)}))||[];
 const toggle=(key,fn)=>access.mutate(key,fn);
 const saveDefaults=async()=>{const error=owner?'':validateDefaults(defaults,d);if(error){return access.mutate('defaults',()=>Promise.reject(new Error(error)))} await toggle('defaults',()=>accessControlService.saveDefaults({tenantId,userId:user.id,defaults}))};
 return <Sheet open={Boolean(user)} onOpenChange={open=>{if(!open){onChanged?.();onClose()}}}><SheetContent side="left" className="max-w-3xl" dir="rtl"><SheetDismissButton/><SheetHeader><SheetTitle>{memberName(user)}</SheetTitle><SheetDescription>إدارة الأدوار ونطاق العمل والإعدادات الافتراضية. الحفظ يتم فور كل تعديل.</SheetDescription></SheetHeader><SheetBody className="space-y-4 bg-slate-50">
 {access.status==='loading'?<p className="py-16 text-center text-sm font-bold text-slate-500">جاري تحميل تفاصيل المستخدم...</p>:null}{access.error?<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{access.error}</div>:null}
 {d?<><AccessSection title="معلومات المستخدم"><div className="flex flex-wrap gap-2"><Badge>{roleLabel(user.role)}</Badge><Badge variant={user.isActive?'success':'warning'}>{user.isActive?'نشط':'غير نشط'}</Badge>{user.email?<Badge>{user.email}</Badge>:null}</div></AccessSection>
 <AccessSection title="الوصول للتطبيقات" description="الوصول الفعلي الناتج من المجموعات الحالية والتطبيقات المثبتة.">{d.installedApps.map(app=><div key={app.id} className="flex items-center justify-between rounded-lg border bg-white px-3 py-2"><span className="text-sm font-bold">{app.name}</span><Badge variant={owner||app.hasAccess?'success':'warning'}>{owner||app.hasAccess?'متاح':'غير متاح'}</Badge></div>)}</AccessSection>
 {owner?<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><h3 className="font-black text-emerald-900">وصول كامل لجميع الفروع والموارد</h3><p className="mt-1 text-sm text-emerald-700">صلاحيات المالك تلقائية؛ لا تُنشأ له صفوف إسناد. يمكن تعديل إعداداته الافتراضية فقط.</p></div>:<>
 <AccessSection title="الأدوار والصلاحيات" description="المجموعات الحالية فقط؛ لا توجد مصفوفة صلاحيات تفصيلية في هذه المرحلة.">{d.groups.map(g=><AccessCheck key={g.id} label={g.name} hint={g.description||g.code} checked={groupIds.has(g.id)} pending={access.pending===`group:${g.id}`} onChange={enabled=>toggle(`group:${g.id}`,()=>accessControlService.toggleGroup({tenantId,userId:user.id,groupId:g.id,enabled}))}/>)}</AccessSection>
 <AccessSection title="الفروع المسموحة" description="لن يمكن إزالة فرع قبل إزالة نقاط البيع ومواقع المخزون التابعة أو تغيير الإعداد الافتراضي.">{d.branches.map(b=><AccessCheck key={b.id} label={b.name} checked={branchIds.has(b.id)} pending={access.pending===`branch:${b.id}`} onChange={enabled=>toggle(`branch:${b.id}`,()=>accessControlService.toggleBranch({tenantId,userId:user.id,branchId:b.id,enabled}))}/>)}</AccessSection>
 <AccessSection title="نقاط البيع المسموحة" description="تظهر نقاط البيع داخل الفروع المسموحة فقط.">{grouped(d.poses).map(x=><div key={x.branch.id}><p className="mb-2 mt-3 text-xs font-black text-slate-500">{x.branch.name}</p>{x.items.map(p=><AccessCheck key={p.id} label={p.name} checked={posIds.has(p.id)} pending={access.pending===`pos:${p.id}`} onChange={enabled=>toggle(`pos:${p.id}`,()=>accessControlService.togglePos({tenantId,userId:user.id,posId:p.id,branchId:p.branch_id,enabled}))}/>)}</div>)}</AccessSection>
 <AccessSection title="مواقع المخزون المسموحة">{grouped(d.stocks).map(x=><div key={x.branch.id}><p className="mb-2 mt-3 text-xs font-black text-slate-500">{x.branch.name}</p>{x.items.map(s=><AccessCheck key={s.id} label={s.name} hint={s.code} checked={stockIds.has(s.id)} pending={access.pending===`stock:${s.id}`} onChange={enabled=>toggle(`stock:${s.id}`,()=>accessControlService.toggleStock({tenantId,userId:user.id,stockLocationId:s.id,branchId:s.branch_id,enabled}))}/>)}</div>)}</AccessSection>
 <AccountsAccess tenantId={tenantId} userId={user.id} details={d} pending={access.pending} mutate={toggle}/></>}
 <AccessSection title="الإعدادات الافتراضية" description="اختر فقط من الموارد المسموحة. لن يتغير أي اختيار تلقائيًا."><Select label="الفرع الافتراضي" value={defaults?.defaultBranchId||''} onChange={v=>setDefaults(x=>({...x,defaultBranchId:v,defaultPosId:'',defaultStockLocationId:''}))} items={owner?d.branches:d.branches.filter(b=>branchIds.has(b.id))}/><Select label="نقطة البيع الافتراضية" value={defaults?.defaultPosId||''} onChange={v=>setDefaults(x=>({...x,defaultPosId:v}))} items={d.poses.filter(p=>(owner||posIds.has(p.id))&&p.branch_id===defaults?.defaultBranchId)}/><Select label="موقع المخزون الافتراضي" value={defaults?.defaultStockLocationId||''} onChange={v=>setDefaults(x=>({...x,defaultStockLocationId:v}))} items={d.stocks.filter(s=>(owner||stockIds.has(s.id))&&s.branch_id===defaults?.defaultBranchId)}/><Button disabled={access.pending==='defaults'} onClick={saveDefaults}>{access.pending==='defaults'?'جاري الحفظ...':'حفظ الإعدادات الافتراضية'}</Button></AccessSection></>:null}
 </SheetBody></SheetContent></Sheet>;
}
function Select({label,value,onChange,items}){return <label className="block text-sm font-bold text-slate-700">{label}<select className="mt-1 h-11 w-full rounded-xl border border-slate-200 bg-white px-3" value={value} onChange={e=>onChange(e.target.value)}><option value="">بدون اختيار</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
