import { KeyRound, ShieldCheck, Users } from 'lucide-react';
import { useState } from 'react';
import { useWorkspace } from '@/features/workspace/hooks/useWorkspace';
import { useGroupSummaries, useUsers } from '../hooks/useAccessControl';
import { SectionTabs } from '../shared/AccessControlPrimitives';
import { UsersList } from '../users/UsersList';
import { UserDetails } from '../users/UserDetails';
import { RolesList } from '../roles/RolesList';
import { RoleForm } from '../roles/RoleForm';
import { RoleDetails } from '../roles/RoleDetails';
import { PermissionCatalog } from '../permissions/PermissionCatalog';

const tabs=[{value:'users',label:'المستخدمون',icon:Users},{value:'roles',label:'الأدوار',icon:ShieldCheck},{value:'permissions',label:'الصلاحيات',icon:KeyRound}];
export function AccessControlSettings(){const {tenant,tenantUser}=useWorkspace();const owner=tenantUser?.role==='owner';const [tab,setTab]=useState('users');const [term,setTerm]=useState('');const [statusFilter,setStatusFilter]=useState('all');const [selectedUser,setSelectedUser]=useState(null);const [selectedRole,setSelectedRole]=useState(null);const [creatingRole,setCreatingRole]=useState(false);const users=useUsers(tenant?.id,owner&&tab==='users');const groups=useGroupSummaries(tenant?.id,owner&&(tab==='roles'||Boolean(selectedRole)));if(!owner)return <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-800">صفحة الأدوار والصلاحيات متاحة لمالك الشركة فقط.</div>;const openRole=role=>{setSelectedUser(null);setSelectedRole(role)};const openUser=user=>{setSelectedRole(null);setSelectedUser(user)};const afterCreate=async role=>{await groups.reload();setSelectedRole(Array.isArray(role)?role[0]:role)};return <div className="mx-auto max-w-6xl space-y-6" dir="rtl"><header className="border-b border-slate-100 pb-5"><h1 className="text-2xl font-black text-slate-950">الأدوار والصلاحيات</h1><p className="mt-2 text-sm text-slate-500">إدارة وصول المستخدمين والأدوار ونطاق العمل.</p></header><div className="overflow-x-auto"><SectionTabs value={tab} onChange={value=>{setTab(value);setSelectedUser(null);setSelectedRole(null)}} items={tabs} label="أقسام الأدوار والصلاحيات"/></div>{tab==='users'?<UsersList users={users} term={term} onTermChange={setTerm} statusFilter={statusFilter} onStatusFilterChange={setStatusFilter} onSelect={openUser}/>:null}{tab==='roles'?<RolesList groups={groups} onSelect={openRole} onCreate={()=>setCreatingRole(true)}/>:null}{tab==='permissions'?<PermissionCatalog active onOpenRole={role=>{setTab('roles');openRole(role)}}/>:null}<UserDetails tenantId={tenant?.id} user={selectedUser} onClose={()=>setSelectedUser(null)} onChanged={users.reload} onOpenRole={role=>{setTab('roles');openRole(role)}}/><RoleDetails tenantId={tenant?.id} role={selectedRole} onClose={()=>setSelectedRole(null)} onSaved={groups.reload} onOpenUser={user=>{setTab('users');openUser(user)}}/><RoleForm open={creatingRole} onClose={()=>setCreatingRole(false)} onCreated={afterCreate}/></div>}
