export const ROUTES = {
  landing: '/',
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
  checkingSession: '/checking-session',
  onboarding: '/onboarding',
  app: '/app',
  appDynamic: '/app/:appCode/*',
  admin: '/admin',
  dashboard: '/admin',
  partners: '/app/partners',
  products: '/app/products',
  inventory: '/app/inventory',
  adminPos: '/app/pos',
  invoices: '/app/sales',
  payments: '/apps/accounting',
  contracts: '/app/contracts',
  settings: '/app/settings',
  settingsCashLocations: '/app/settings/accounting/cash-locations',
  settingsTeam: '/app/settings/team',
  settingsPermissions: '/app/settings/permissions',
  paymentSettings: '/app/settings?section=accounting&tab=methods',
  team: '/app/settings/team',
};
