export const ROUTES = {
  landing: '/',
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
  checkingSession: '/checking-session',
  onboarding: '/onboarding',
  app: '/app',
  appDynamic: '/app/:appCode/*',
  admin: '/admin',
  dashboard: '/admin',
  partners: '/app/partners',
  products: '/apps/inventory/products',
  inventory: '/apps/inventory',
  adminPos: '/app/pos',
  invoices: '/app/sales',
  payments: '/apps/accounting',
  contracts: '/app/contracts',
  settings: '/app/settings',
  settingsFinancial: '/app/settings/financial',
  settingsMoneyDestinations: '/app/settings/financial/money-destinations',
  settingsBranches: '/app/settings/branches',
  settingsTeam: '/app/settings/team',
  settingsPermissions: '/app/settings/permissions',
  team: '/app/settings/team',
};
