import { CheckCircle2, LoaderCircle, RotateCcw } from 'lucide-react';
import { Button } from '@/core/ui/button';
import { Sheet, SheetBody, SheetContent, SheetDescription, SheetDismissButton, SheetFooter, SheetHeader, SheetTitle } from '@/core/ui/sheet';
import { useSaleReturn } from '@/features/sales/hooks/useSaleReturn';

const quantity = (value) => Number(value || 0).toLocaleString('ar-EG', { maximumFractionDigits: 4 });
const money = (value, currency) => `${Number(value || 0).toLocaleString('ar-EG', { maximumFractionDigits: 2 })} ${currency}`;

export function SaleReturnDialog({ open, onOpenChange, tenantId, sale, initialEligibility, onReturned, onVersionConflict, onTargetRefresh }) {
  const state = useSaleReturn({ open, tenantId, sale, initialEligibility, onReturned, onVersionConflict, onTargetRefresh });
  const close = (next) => { if (!state.submitting) onOpenChange?.(next); };
  return <Sheet open={open} onOpenChange={close}><SheetContent side="bottom" dir="rtl" className="mx-auto max-h-[94vh] w-full max-w-2xl overflow-x-hidden" aria-describedby="sale-return-description" onEscapeKeyDown={(event) => { if (state.submitting) event.preventDefault(); }} onPointerDownOutside={(event) => { if (state.submitting) event.preventDefault(); }}>
    <SheetDismissButton aria-label="إغلاق نافذة المرتجع" disabled={state.submitting} />
    <SheetHeader className="pl-16"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-orange-50 text-orange-700"><RotateCcw className="h-5 w-5" /></span><div><SheetTitle>مرتجع بيع</SheetTitle><SheetDescription id="sale-return-description">استلام البضاعة وإنشاء الإشعار الدائن؛ رد الأموال إجراء منفصل.</SheetDescription></div></div></SheetHeader>
    {state.status === 'loading' && !state.eligibility ? <SheetBody><div role="status" className="flex min-h-56 items-center justify-center gap-2 font-bold text-slate-600"><LoaderCircle className="h-6 w-6 animate-spin" />جاري تحميل البنود القابلة للإرجاع...</div></SheetBody> : null}
    {state.error && !state.eligibility ? <SheetBody><p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-900">{state.error.message}</p><Button type="button" variant="secondary" className="mt-3" onClick={state.retryEligibility}>إعادة المحاولة</Button></SheetBody> : null}
    {state.result ? <><SheetBody><div role="status" className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-emerald-950"><CheckCircle2 className="h-8 w-8" /><h3 className="mt-2 text-lg font-black">تم تسجيل المرتجع</h3><p className="mt-1 text-sm">{state.result.returnNumber} · {money(state.result.amount, sale.currencyCode)}</p><p className="mt-2 text-sm">خُفّضت الذمة بـ{money(state.result.arAppliedAmount, sale.currencyCode)}، والمتاح للرد {money(state.result.refundableAmount, sale.currencyCode)}.</p></div></SheetBody><SheetFooter><Button type="button" onClick={() => close(false)}>إغلاق</Button></SheetFooter></> : null}
    {state.eligibility && !state.result ? <form className="contents" onSubmit={state.submit} noValidate><SheetBody className="space-y-4 overflow-x-hidden">
      <dl className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><dt className="text-xs font-bold text-slate-500">رقم البيع</dt><dd className="mt-1 font-black">{state.eligibility.saleNumber}</dd></div><div className="rounded-xl bg-slate-50 p-3"><dt className="text-xs font-bold text-slate-500">العميل</dt><dd className="mt-1 font-black">{state.eligibility.customer.name}</dd></div></dl>
      {!state.eligibility.canReturn ? <p role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-950">{state.eligibility.reasonMessage}</p> : null}
      {state.eligibility.lines.filter((line) => line.returnableQuantity > 0).map((line) => <article key={line.saleLineId} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex justify-between gap-3"><div><h3 className="font-black">{line.productName}</h3><p className="mt-1 text-xs text-slate-500">مُسلّم {quantity(line.deliveredQuantity)} · سبق إرجاعه {quantity(line.alreadyReturnedQuantity)} · متاح {quantity(line.returnableQuantity)}</p></div><span className="text-sm font-black text-orange-700">{money(line.returnableAmount, state.eligibility.currencyCode)}</span></div>
        {line.kind === 'serial' ? <div className="mt-3 space-y-2">{line.serializedUnits.map((unit) => <label key={unit.trackingUnitId} className="flex min-h-14 cursor-pointer items-start gap-3 rounded-xl border border-orange-100 bg-orange-50/40 p-3"><input type="checkbox" className="mt-1 h-5 w-5 accent-orange-600" checked={state.selection[line.saleLineId]?.units?.[unit.trackingUnitId] === true} onChange={(event) => state.setUnit(line.saleLineId, unit.trackingUnitId, event.target.checked)} /><span className="text-sm"><strong>شاسيه: <span dir="ltr">{unit.chassisNumber}</span></strong>{unit.engineNumber ? <span className="mt-1 block">موتور: <span dir="ltr">{unit.engineNumber}</span></span> : null}</span></label>)}</div> : <label className="mt-3 block text-sm font-black">كمية المرتجع<input type="number" inputMode="decimal" min="0" max={line.returnableQuantity} step="0.0001" value={state.selection[line.saleLineId]?.quantity || ''} onChange={(event) => state.setQuantity(line.saleLineId, event.target.value)} className="mt-2 h-12 w-full rounded-xl border border-slate-300 px-3 outline-none focus:border-orange-500 focus:ring-2 focus:ring-orange-100" /></label>}
        {line.kind === 'service' ? <p className="mt-2 text-xs font-bold text-blue-700">تخفيض تجاري ومالي فقط — لا توجد حركة مخزون.</p> : null}
      </article>)}
      {state.eligibility.lines.some((line) => line.kind !== 'service' && line.returnableQuantity > 0) ? <label className="block text-sm font-black">موقع استلام المرتجع<select value={state.destinationId} onChange={(event) => state.setDestinationId(event.target.value)} className="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-white px-3"><option value="">اختر الموقع</option>{state.eligibility.destinations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : null}
      <label className="block text-sm font-black">سبب المرتجع<textarea rows={3} maxLength={1000} value={state.reason} onChange={(event) => state.setReason(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 p-3 font-normal" placeholder="اكتب سببًا واضحًا" /></label>
      <div className="rounded-xl bg-slate-950 p-4 text-white"><p className="text-xs text-slate-300">قيمة المرتجع المختار</p><p className="mt-1 text-xl font-black">{money(state.total, state.eligibility.currencyCode)}</p></div>
      {state.error ? <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-900">{state.error.message}</p> : null}
    </SheetBody><SheetFooter className="flex-wrap"><Button type="button" variant="secondary" onClick={() => close(false)} disabled={state.submitting}>رجوع</Button><Button type="submit" disabled={Boolean(state.issue) || state.submitting || !state.eligibility.canReturn} title={state.issue || undefined}>{state.submitting ? <><LoaderCircle className="h-4 w-4 animate-spin" />جاري التنفيذ...</> : 'تأكيد المرتجع'}</Button></SheetFooter></form> : null}
  </SheetContent></Sheet>;
}
