import { ArrowLeft, ArrowRight, LoaderCircle, Repeat2 } from 'lucide-react';
import { Button } from '@/core/ui/button';
import { ProductSelector } from '@/features/sales/create/ProductSelector';
import { SaleItemRow } from '@/features/sales/create/SaleItemRow';
import { Sheet, SheetBody, SheetContent, SheetDescription, SheetDismissButton, SheetFooter, SheetHeader, SheetTitle } from '@/core/ui/sheet';
import { useSaleExchange } from '@/features/sales/hooks/useSaleExchange';

const quantity = (value) => Number(value || 0).toLocaleString('ar-EG', { maximumFractionDigits: 4 });
const money = (value, currency) => `${Number(value || 0).toLocaleString('ar-EG', { maximumFractionDigits: 2 })} ${currency}`;

function ReturnStep({ state }) {
  const returnEligibility = state.eligibility.returnEligibility;
  return <div className="space-y-4">
    <dl className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><dt className="text-xs font-bold text-slate-500">البيع الأصلي</dt><dd className="mt-1 font-black">{state.eligibility.saleNumber}</dd></div><div className="rounded-xl bg-slate-50 p-3"><dt className="text-xs font-bold text-slate-500">العميل</dt><dd className="mt-1 font-black">{state.eligibility.customer.name}</dd></div></dl>
    {returnEligibility.lines.filter((line) => line.returnableQuantity > 0).map((line) => <article key={line.saleLineId} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex justify-between gap-3"><div><h3 className="font-black">{line.productName}</h3><p className="mt-1 text-xs text-slate-500">مُسلّم {quantity(line.deliveredQuantity)} · سبق إرجاعه {quantity(line.alreadyReturnedQuantity)} · متاح {quantity(line.returnableQuantity)}</p></div><strong className="text-violet-700">{money(line.returnableAmount, state.eligibility.currencyCode)}</strong></div>
      {line.kind === 'serial' ? <div className="mt-3 space-y-2">{line.serializedUnits.map((unit) => <label key={unit.trackingUnitId} className="flex min-h-14 cursor-pointer gap-3 rounded-xl border border-violet-100 bg-violet-50/40 p-3"><input type="checkbox" className="mt-1 h-5 w-5 accent-violet-600" checked={state.returnSelection[line.saleLineId]?.units?.[unit.trackingUnitId] === true} onChange={(event) => state.setUnit(line.saleLineId, unit.trackingUnitId, event.target.checked)} /><span className="text-sm"><strong>شاسيه: <span dir="ltr">{unit.chassisNumber}</span></strong>{unit.engineNumber ? <span className="mt-1 block">موتور: <span dir="ltr">{unit.engineNumber}</span></span> : null}</span></label>)}</div> : <label className="mt-3 block text-sm font-black">كمية المرتجع<input type="number" inputMode="decimal" min="0" max={line.returnableQuantity} step="0.0001" value={state.returnSelection[line.saleLineId]?.quantity || ''} onChange={(event) => state.setQuantity(line.saleLineId, event.target.value)} className="mt-2 h-12 w-full rounded-xl border border-slate-300 px-3" /></label>}
      {line.kind === 'service' ? <p className="mt-2 text-xs font-bold text-blue-700">Credit تجاري فقط — لا توجد حركة مخزون.</p> : null}
    </article>)}
    {returnEligibility.lines.some((line) => line.kind !== 'service' && line.returnableQuantity > 0) ? <label className="block text-sm font-black">موقع استلام المرتجع<select value={state.returnDestinationId} onChange={(event) => state.setReturnDestinationId(event.target.value)} className="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-white px-3"><option value="">اختر الموقع</option>{returnEligibility.destinations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : null}
    <label className="block text-sm font-black">سبب الاستبدال<textarea rows={3} maxLength={1000} value={state.reason} onChange={(event) => state.setReason(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 p-3 font-normal" placeholder="اكتب سببًا واضحًا" /></label>
    <div className="rounded-xl bg-slate-950 p-4 text-white"><p className="text-xs text-slate-300">قيمة المنتجات المرتجعة</p><p className="mt-1 text-xl font-black">{money(state.returnedTotal, state.eligibility.currencyCode)}</p></div>
  </div>;
}

function ReplacementStep({ state, tenantId }) {
  const hasGoods = state.replacementLines.some((line) => line.product.productType === 'goods');
  return <div className="space-y-4">
    <div><h3 className="font-black">المنتج البديل</h3><p className="mt-1 text-sm text-slate-500">ابحث وأضف بنود Sale Draft عادية. لا يتم حجز المخزون الآن.</p></div>
    <ProductSelector tenantId={tenantId} onSelect={state.addProduct} />
    {hasGoods ? <label className="block text-sm font-black">موقع مخزون البيع البديل<select value={state.replacementLocationId} onChange={(event) => state.setReplacementLocationId(event.target.value)} className="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-white px-3"><option value="">اختر الموقع</option>{state.eligibility.replacementLocations.map((item) => <option key={item.id} value={item.id}>{item.name}{item.code ? ` — ${item.code}` : ''}</option>)}</select></label> : null}
    {!state.replacementLines.length ? <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-7 text-center text-sm font-bold text-slate-500">لم تتم إضافة منتج بديل بعد.</div> : <div className="space-y-3">{state.replacementLines.map((line, index) => <SaleItemRow key={line.key} tenantId={tenantId} branchId={state.eligibility.branch.id} locationId={state.replacementLocationId} line={line} index={index} disabled={false} onChange={(changes) => state.updateLine(line.key, changes)} onRemove={() => state.removeLine(line.key)} />)}</div>}
    <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-orange-50 p-3"><p className="text-xs font-bold text-orange-700">قيمة المرتجع</p><p className="mt-1 font-black">{money(state.returnedTotal, state.eligibility.currencyCode)}</p></div><div className="rounded-xl bg-violet-50 p-3"><p className="text-xs font-bold text-violet-700">مسودة البديل</p><p className="mt-1 font-black">{money(state.replacementTotal, state.eligibility.currencyCode)}</p></div><div className="rounded-xl bg-slate-900 p-3 text-white"><p className="text-xs text-slate-300">فرق تقديري فقط</p><p className="mt-1 font-black">{money(state.estimatedDifference, state.eligibility.currencyCode)}</p></div></div>
    <p className="rounded-xl bg-blue-50 p-3 text-xs font-bold text-blue-800">لا يتم تحصيل أو رد أي مبلغ هنا. يُراجع البيع البديل ثم يُؤكد ويُسوّى ويُسلّم عبر المسارات المعتادة.</p>
  </div>;
}

export function SaleExchangeDialog({ open, onOpenChange, tenantId, sale, initialEligibility, onStarted, onVersionConflict, onTargetRefresh }) {
  const state = useSaleExchange({ open, tenantId, sale, initialEligibility, onStarted, onVersionConflict, onTargetRefresh });
  const close = (next) => { if (!state.submitting) onOpenChange?.(next); };
  const returnStepIssue = state.step === 1 && (!state.reason.trim() || state.returnedTotal <= 0 || (state.eligibility?.returnEligibility?.lines.some((line) => line.kind !== 'service' && state.returnSelection[line.saleLineId] && (Number(state.returnSelection[line.saleLineId].quantity || 0) > 0 || Object.values(state.returnSelection[line.saleLineId].units || {}).some(Boolean))) && !state.returnDestinationId));
  return <Sheet open={open} onOpenChange={close}><SheetContent side="bottom" dir="rtl" className="mx-auto max-h-[95vh] w-full max-w-3xl overflow-x-hidden" aria-describedby="sale-exchange-description" onEscapeKeyDown={(event) => { if (state.submitting) event.preventDefault(); }} onPointerDownOutside={(event) => { if (state.submitting) event.preventDefault(); }}>
    <SheetDismissButton aria-label="إغلاق نافذة الاستبدال" disabled={state.submitting} />
    <SheetHeader className="pl-16"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-700"><Repeat2 className="h-5 w-5" /></span><div><SheetTitle>استبدال منتج</SheetTitle><SheetDescription id="sale-exchange-description">مرتجع Canonical ثم مسودة بيع بديلة مستقلة.</SheetDescription></div></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs font-black"><span className={`rounded-full px-3 py-2 text-center ${state.step === 1 ? 'bg-violet-700 text-white' : 'bg-slate-100 text-slate-500'}`}>1. المنتج المرتجع</span><span className={`rounded-full px-3 py-2 text-center ${state.step === 2 ? 'bg-violet-700 text-white' : 'bg-slate-100 text-slate-500'}`}>2. المنتج البديل</span></div></SheetHeader>
    {state.status === 'loading' && !state.eligibility ? <SheetBody><div role="status" className="flex min-h-56 items-center justify-center gap-2 font-bold text-slate-600"><LoaderCircle className="h-6 w-6 animate-spin" />جاري تحميل أهلية الاستبدال...</div></SheetBody> : null}
    {state.error && !state.eligibility ? <SheetBody><p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-900">{state.error.message}</p><Button type="button" variant="secondary" className="mt-3" onClick={state.reload}>إعادة المحاولة</Button></SheetBody> : null}
    {state.eligibility ? <form className="contents" onSubmit={state.submit} noValidate><SheetBody className="overflow-x-hidden">{state.step === 1 ? <ReturnStep state={state} /> : <ReplacementStep state={state} tenantId={tenantId} />}{state.error ? <p role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-900">{state.error.message}</p> : null}</SheetBody><SheetFooter className="flex-wrap">{state.step === 1 ? <><Button type="button" variant="secondary" onClick={() => close(false)}>إلغاء</Button><Button type="button" disabled={Boolean(returnStepIssue)} onClick={() => state.setStep(2)}>التالي<ArrowLeft className="h-4 w-4" /></Button></> : <><Button type="button" variant="secondary" disabled={state.submitting} onClick={() => state.setStep(1)}><ArrowRight className="h-4 w-4" />السابق</Button><Button type="submit" disabled={Boolean(state.issue) || state.submitting}>{state.submitting ? <><LoaderCircle className="h-4 w-4 animate-spin" />جاري إنشاء الاستبدال...</> : 'إنشاء الاستبدال'}</Button></>}</SheetFooter></form> : null}
  </SheetContent></Sheet>;
}
