begin;

create or replace function public.guard_internal_transfer_accounting_state()returns trigger language plpgsql set search_path=pg_catalog,public as $$begin
 if new.accounting_state is not distinct from old.accounting_state and new.accounting_reversed_by is not distinct from old.accounting_reversed_by and new.accounting_reversed_at is not distinct from old.accounting_reversed_at and new.accounting_reversal_id is not distinct from old.accounting_reversal_id then return new;end if;
 if current_setting('app.internal_transfer_reversal_contract',true)=new.id::text and old.accounting_state='active'and new.accounting_state='reversed'then return new;end if;raise exception using errcode='42501',message='TRANSFER_ACCOUNTING_STATE_REQUIRES_REVERSAL_CONTRACT';end $$;
create trigger financial_internal_transfer_accounting_state_guard before update of accounting_state,accounting_reversed_by,accounting_reversed_at,accounting_reversal_id on public.financial_internal_transfers for each row execute function public.guard_internal_transfer_accounting_state();

create or replace function public.reverse_internal_transfer_accounting(p_tenant uuid,p_transfer uuid,p_reason text,p_idempotency text,p_reversal_date date default current_date)returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare t public.financial_internal_transfers%rowtype;existing public.financial_accounting_reversals%rowtype;rid uuid:=gen_random_uuid();fp text;num text;actor uuid:=public.current_tenant_user_id();orig uuid;rev uuid;stage text;result jsonb:='[]';reason text:=nullif(btrim(p_reason),'');
begin if reason is null then raise exception using errcode='22023',message='ACCOUNTING_REVERSAL_REASON_REQUIRED';end if;if nullif(btrim(coalesce(p_idempotency,'')),'')is null then raise exception using errcode='22023',message='ACCOUNTING_REVERSAL_IDEMPOTENCY_REQUIRED';end if;
 fp:=encode(extensions.digest(jsonb_build_object('domain','internal_transfer','id',p_transfer,'reason',reason,'date',p_reversal_date)::text,'sha256'),'hex');perform pg_advisory_xact_lock(hashtextextended('transfer_reversal:'||p_tenant||':'||p_transfer,0));
 select*into existing from public.financial_accounting_reversals where tenant_id=p_tenant and idempotency_key=btrim(p_idempotency);if found then if existing.request_fingerprint<>fp then raise exception using errcode='23505',message='ACCOUNTING_REVERSAL_IDEMPOTENCY_PAYLOAD_MISMATCH';end if;return jsonb_build_object('reversal_id',existing.id,'reversal_number',existing.reversal_number,'moves',(select coalesce(jsonb_agg(jsonb_build_object('stage',stage,'move_id',reversal_move_id)order by id),'[]')from public.financial_accounting_reversal_move_links where reversal_id=existing.id),'idempotent_replay',true);end if;
 select*into t from public.financial_internal_transfers where id=p_transfer and tenant_id=p_tenant for update;if not found then raise exception using errcode='P0002',message='INTERNAL_TRANSFER_NOT_FOUND';end if;
 perform public.assert_financial_authorized(p_tenant,'financial.transfer.confirm',null,null,t.source_branch_id,t.accounting_state='active');perform*from public.resolve_internal_transfer_destination(p_tenant,t.source_destination_id,'financial.transfer.confirm','transfer_from',t.source_branch_id);perform*from public.resolve_internal_transfer_destination(p_tenant,t.destination_destination_id,'financial.transfer.confirm','transfer_to',t.destination_branch_id);
 if t.accounting_state<>'active'then raise exception using errcode='23514',message='ACCOUNTING_EFFECT_ALREADY_REVERSED';end if;if t.status='draft'then raise exception using errcode='23514',message='TRANSFER_HAS_NO_ACCOUNTING_EFFECT';end if;
 if exists(select 1 from public.financial_accounting_reversals where tenant_id=p_tenant and domain_type='internal_transfer'and domain_id=t.id)then raise exception using errcode='23514',message='ACCOUNTING_EFFECT_ALREADY_REVERSED';end if;
 num:=public.next_financial_accounting_reversal_number(p_tenant);perform set_config('app.financial_accounting_reversal_contract',rid::text,true);insert into public.financial_accounting_reversals(id,tenant_id,reversal_number,domain_type,domain_id,reason,reversal_date,idempotency_key,request_fingerprint,requested_by,completed_by,metadata)values(rid,p_tenant,num,'internal_transfer',t.id,reason,p_reversal_date,btrim(p_idempotency),fp,actor,actor,jsonb_build_object('transfer_mode',t.transfer_mode,'operational_status',t.status));
 if t.transfer_mode='immediate'then select account_move_id into orig from public.financial_internal_transfer_accounting_links where tenant_id=p_tenant and transfer_id=t.id and entry_type='immediate';if orig is null then raise exception using errcode='23514',message='TRANSFER_ACCOUNTING_LINK_MISSING';end if;rev:=public.create_reversing_account_move(rid,p_tenant,orig,'transfer_immediate',p_reversal_date,actor);insert into public.financial_internal_transfer_accounting_links(tenant_id,transfer_id,account_move_id,entry_type,created_by)values(p_tenant,t.id,rev,'reversal_immediate',actor);result:=result||jsonb_build_object('stage','reversal_immediate','move_id',rev);
 else
  if t.status in('received','confirmed')then select account_move_id into orig from public.financial_internal_transfer_accounting_links where tenant_id=p_tenant and transfer_id=t.id and entry_type='receive';if orig is null then raise exception using errcode='23514',message='TRANSFER_RECEIVE_LINK_MISSING';end if;rev:=public.create_reversing_account_move(rid,p_tenant,orig,'transfer_receive',p_reversal_date,actor);insert into public.financial_internal_transfer_accounting_links(tenant_id,transfer_id,account_move_id,entry_type,created_by)values(p_tenant,t.id,rev,'reversal_receive',actor);result:=result||jsonb_build_object('stage','reversal_receive','move_id',rev);end if;
  select account_move_id into orig from public.financial_internal_transfer_accounting_links where tenant_id=p_tenant and transfer_id=t.id and entry_type='send';if orig is null then raise exception using errcode='23514',message='TRANSFER_SEND_LINK_MISSING';end if;rev:=public.create_reversing_account_move(rid,p_tenant,orig,'transfer_send',p_reversal_date,actor);insert into public.financial_internal_transfer_accounting_links(tenant_id,transfer_id,account_move_id,entry_type,created_by)values(p_tenant,t.id,rev,'reversal_send',actor);result:=result||jsonb_build_object('stage','reversal_send','move_id',rev);
 end if;
 perform set_config('app.internal_transfer_reversal_contract',t.id::text,true);update public.financial_internal_transfers set accounting_state='reversed',accounting_reversed_by=actor,accounting_reversed_at=now(),accounting_reversal_id=rid where id=t.id;
 insert into public.financial_accounting_reversal_events(tenant_id,reversal_id,event_type,actor_user_id,reason,metadata)values(p_tenant,rid,'transfer_accounting_reversed',actor,reason,jsonb_build_object('moves',result));return jsonb_build_object('reversal_id',rid,'reversal_number',num,'moves',result,'idempotent_replay',false);end $$;

drop trigger financial_advance_application_events_guard on public.financial_advance_application_events;
alter table public.financial_advance_application_events drop constraint financial_advance_application_events_event_type_check,add constraint financial_advance_application_events_event_type_check check(event_type in('applied','advance_unapplied'));
create or replace function public.guard_financial_advance_application_event()returns trigger language plpgsql set search_path=pg_catalog,public as $$begin
 if tg_op<>'INSERT'then raise exception using errcode='23514',message='FINANCIAL_ADVANCE_APPLICATION_EVENT_IMMUTABLE';end if;
 if(current_setting('app.financial_advance_application_contract',true)=new.application_id::text and new.event_type='applied')or(current_setting('app.financial_advance_unapplication_contract',true)=new.application_id::text and new.event_type='advance_unapplied')then return new;end if;raise exception using errcode='42501',message='FINANCIAL_ADVANCE_APPLICATION_EVENT_REQUIRES_CONTRACT';end $$;
create trigger financial_advance_application_events_guard before insert or update or delete on public.financial_advance_application_events for each row execute function public.guard_financial_advance_application_event();

create or replace function public.unapply_financial_advance(p_tenant_id uuid,p_application_id uuid,p_reason text,p_idempotency_key text default null,p_reversal_date date default current_date)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare a public.financial_advance_applications%rowtype;existing public.financial_accounting_reversals%rowtype;rid uuid:=gen_random_uuid();fp text;num text;actor uuid:=public.current_tenant_user_id();rev uuid;reason text:=nullif(btrim(p_reason),'');adv_rev uuid;target_rev uuid;pid uuid;begin
 if reason is null then raise exception using errcode='22023',message='ACCOUNTING_REVERSAL_REASON_REQUIRED';end if;if nullif(btrim(coalesce(p_idempotency_key,'')),'')is null then raise exception using errcode='22023',message='ACCOUNTING_REVERSAL_IDEMPOTENCY_REQUIRED';end if;
 fp:=encode(extensions.digest(jsonb_build_object('domain','advance_application','id',p_application_id,'reason',reason,'date',p_reversal_date)::text,'sha256'),'hex');perform pg_advisory_xact_lock(hashtextextended('advance_unapplication:'||p_tenant_id||':'||p_application_id,0));
 select*into existing from public.financial_accounting_reversals where tenant_id=p_tenant_id and idempotency_key=btrim(p_idempotency_key);if found then if existing.request_fingerprint<>fp then raise exception using errcode='23505',message='ACCOUNTING_REVERSAL_IDEMPOTENCY_PAYLOAD_MISMATCH';end if;return jsonb_build_object('application_id',p_application_id,'reversal_id',existing.id,'reversal_number',existing.reversal_number,'idempotent_replay',true);end if;
 select*into a from public.financial_advance_applications where id=p_application_id and tenant_id=p_tenant_id for update;if not found then raise exception using errcode='P0002',message='ADVANCE_APPLICATION_NOT_FOUND';end if;
 perform public.assert_financial_authorized(p_tenant_id,'financial.reconciliation.manage',null,null,null,a.status='active');if a.status<>'active'then raise exception using errcode='23514',message='ADVANCE_APPLICATION_ALREADY_UNAPPLIED';end if;
 perform public.assert_financial_authorized(p_tenant_id,'financial.reconciliation.manage',(select account_id from public.account_move_lines where id=a.advance_source_line_id),'reconcile',(select branch_id from public.financial_payments where id=a.advance_payment_id),true);
 perform public.assert_financial_authorized(p_tenant_id,'financial.reconciliation.manage',(select account_id from public.account_move_lines where id=a.target_account_line_id),'reconcile',(select m.branch_id from public.account_move_lines l join public.account_moves m on m.id=l.move_id where l.id=a.target_account_line_id),true);
 if exists(select 1 from public.financial_accounting_reversals where tenant_id=p_tenant_id and domain_type='advance_application'and domain_id=a.id)then raise exception using errcode='23514',message='ACCOUNTING_EFFECT_ALREADY_REVERSED';end if;
 num:=public.next_financial_accounting_reversal_number(p_tenant_id);perform set_config('app.financial_accounting_reversal_contract',rid::text,true);insert into public.financial_accounting_reversals(id,tenant_id,reversal_number,domain_type,domain_id,reason,reversal_date,idempotency_key,request_fingerprint,requested_by,completed_by)values(rid,p_tenant_id,num,'advance_application',a.id,reason,p_reversal_date,btrim(p_idempotency_key),fp,actor,actor);
 perform public.reversal_remove_partial(rid,p_tenant_id,a.advance_partial_reconcile_id,'advance_source');perform public.reversal_remove_partial(rid,p_tenant_id,a.target_partial_reconcile_id,'advance_target');
 rev:=public.create_reversing_account_move(rid,p_tenant_id,a.reclassification_move_id,'advance_reclassification',p_reversal_date,actor);
 select reversal_line_id into adv_rev from public.financial_accounting_reversal_line_links where reversal_id=rid and original_line_id=a.reclassified_advance_line_id;select reversal_line_id into target_rev from public.financial_accounting_reversal_line_links where reversal_id=rid and original_line_id=a.reclassified_target_line_id;
 if(select debit from public.account_move_lines where id=a.reclassified_advance_line_id)>0 then pid:=public.reversal_create_partial(rid,p_tenant_id,a.reclassified_advance_line_id,adv_rev,a.amount,actor,'reclassification_cleanup_advance');else pid:=public.reversal_create_partial(rid,p_tenant_id,adv_rev,a.reclassified_advance_line_id,a.amount,actor,'reclassification_cleanup_advance');end if;
 if(select debit from public.account_move_lines where id=a.reclassified_target_line_id)>0 then pid:=public.reversal_create_partial(rid,p_tenant_id,a.reclassified_target_line_id,target_rev,a.amount,actor,'reclassification_cleanup_target');else pid:=public.reversal_create_partial(rid,p_tenant_id,target_rev,a.reclassified_target_line_id,a.amount,actor,'reclassification_cleanup_target');end if;
 perform set_config('app.financial_advance_unapplication_contract',a.id::text,true);update public.financial_advance_applications set status='unapplied',unapplied_by=actor,unapplied_at=now(),unapplication_reason=reason,accounting_reversal_id=rid,reversal_reclassification_move_id=rev where id=a.id;
 insert into public.financial_advance_application_events(tenant_id,application_id,event_type,actor_user_id,metadata)values(p_tenant_id,a.id,'advance_unapplied',actor,jsonb_build_object('reason',reason,'accounting_reversal_id',rid,'reversal_move_id',rev));insert into public.financial_accounting_reversal_events(tenant_id,reversal_id,event_type,actor_user_id,reason,metadata)values(p_tenant_id,rid,'advance_unapplied',actor,reason,jsonb_build_object('application_id',a.id,'reversal_move_id',rev));
 return jsonb_build_object('application_id',a.id,'status','unapplied','reversal_id',rid,'reversal_number',num,'reversal_move_id',rev,'idempotent_replay',false);end $$;

alter table public.financial_accounting_reversal_sequences enable row level security;alter table public.financial_accounting_reversals enable row level security;alter table public.financial_accounting_reversal_move_links enable row level security;alter table public.financial_accounting_reversal_line_links enable row level security;alter table public.financial_accounting_reversal_reconcile_links enable row level security;alter table public.financial_accounting_reversal_events enable row level security;
revoke all on public.financial_accounting_reversal_sequences,public.financial_accounting_reversals,public.financial_accounting_reversal_move_links,public.financial_accounting_reversal_line_links,public.financial_accounting_reversal_reconcile_links,public.financial_accounting_reversal_events from public,anon,authenticated;
grant select on public.financial_accounting_reversals,public.financial_accounting_reversal_move_links,public.financial_accounting_reversal_line_links,public.financial_accounting_reversal_reconcile_links,public.financial_accounting_reversal_events to authenticated;
create policy financial_accounting_reversals_read on public.financial_accounting_reversals for select to authenticated using(tenant_id=public.current_tenant_id()and(public.has_permission('financial.audit.view',tenant_id)or public.has_permission('financial.payment.reverse',tenant_id)or public.has_permission('financial.transfer.confirm',tenant_id)or public.has_permission('financial.reconciliation.manage',tenant_id)));
create policy financial_accounting_reversal_move_links_read on public.financial_accounting_reversal_move_links for select to authenticated using(tenant_id=public.current_tenant_id()and exists(select 1 from public.financial_accounting_reversals r where r.id=reversal_id and r.tenant_id=tenant_id));
create policy financial_accounting_reversal_line_links_read on public.financial_accounting_reversal_line_links for select to authenticated using(tenant_id=public.current_tenant_id()and exists(select 1 from public.financial_accounting_reversals r where r.id=reversal_id and r.tenant_id=tenant_id));
create policy financial_accounting_reversal_reconcile_links_read on public.financial_accounting_reversal_reconcile_links for select to authenticated using(tenant_id=public.current_tenant_id()and exists(select 1 from public.financial_accounting_reversals r where r.id=reversal_id and r.tenant_id=tenant_id));
create policy financial_accounting_reversal_events_read on public.financial_accounting_reversal_events for select to authenticated using(tenant_id=public.current_tenant_id()and exists(select 1 from public.financial_accounting_reversals r where r.id=reversal_id and r.tenant_id=tenant_id));

revoke all on function public.next_financial_accounting_reversal_number(uuid),public.create_reversing_account_move(uuid,uuid,uuid,text,date,uuid),public.reversal_create_partial(uuid,uuid,uuid,uuid,numeric,uuid,text),public.reversal_remove_partial(uuid,uuid,uuid,text),public.guard_financial_accounting_reversal_audit(),public.guard_internal_transfer_accounting_state()from public,anon,authenticated;
revoke all on function public.reverse_financial_payment_accounting(uuid,uuid,text,text,date),public.reverse_internal_transfer_accounting(uuid,uuid,text,text,date),public.unapply_financial_advance(uuid,uuid,text,text,date),public.get_financial_reversal_eligibility(uuid,text,uuid)from public,anon;
grant execute on function public.reverse_financial_payment_accounting(uuid,uuid,text,text,date),public.reverse_internal_transfer_accounting(uuid,uuid,text,text,date),public.unapply_financial_advance(uuid,uuid,text,text,date),public.get_financial_reversal_eligibility(uuid,text,uuid)to authenticated;

comment on table public.financial_accounting_reversals is'Canonical immutable completed reversal identity. Reversal neutralizes an erroneous posted fact; it is not a refund.';
comment on function public.create_reversing_account_move(uuid,uuid,uuid,text,date,uuid)is'Internal-only full move inversion. Domain ownership is required through transaction-local reversal context; arbitrary public move reversal is unavailable.';
comment on function public.reverse_internal_transfer_accounting(uuid,uuid,text,text,date)is'Immediate reverses one move; sent-only reverses send; received/confirmed reverses receive first then send, preserving zero transit net.';

commit;
