begin;

insert into public.auth_permissions(code,name,description,resource,action,module_code,permission_type,sort_order,active)values
('financial.refund.create','إنشاء طلب رد مالي','إنشاء Refund مرتبطة برصيد محاسبي قابل للرد.','financial.refund','create','accountant_app','action',170,true),
('financial.refund.submit','إرسال طلب رد مالي','إرسال Refund للمراجعة.','financial.refund','submit','accountant_app','action',171,true),
('financial.refund.confirm','تأكيد تنفيذ رد مالي','تأكيد مسؤولية تنفيذ حركة المال.','financial.refund','confirm','accountant_app','action',172,true),
('financial.refund.post','ترحيل رد مالي','إنشاء وترحيل الأثر المحاسبي للـRefund.','financial.refund','post','accountant_app','action',173,true)
on conflict(code)do update set name=excluded.name,description=excluded.description,resource=excluded.resource,action=excluded.action,module_code=excluded.module_code,permission_type=excluded.permission_type,sort_order=excluded.sort_order,active=true,updated_at=now();

create table public.financial_refund_sequences(tenant_id uuid not null references public.tenants(id)on delete cascade,sequence_year integer not null,next_number bigint not null default 1,updated_at timestamptz not null default now(),primary key(tenant_id,sequence_year),check(next_number>0));
create table public.financial_refunds(
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id)on delete restrict,refund_number text not null,direction text not null,amount numeric(18,2)not null,currency_code text not null,partner_id uuid not null,money_destination_id uuid not null,payment_method_id uuid not null,branch_id uuid,
 source_type text not null,source_account_line_id uuid not null,original_payment_id uuid,source_app text,source_model text,source_id uuid,status text not null default'draft',accounting_state text not null default'unposted',reason text not null,reason_type text,notes text,
 created_by uuid not null,submitted_by uuid,submitted_at timestamptz,confirmed_by uuid,confirmed_at timestamptz,posted_by uuid,posted_at timestamptz,posting_idempotency_key text,rejected_by uuid,rejected_at timestamptz,rejection_reason text,idempotency_key text not null,request_fingerprint text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 foreign key(partner_id,tenant_id)references public.partners(id,tenant_id)on delete restrict,foreign key(money_destination_id,tenant_id)references public.money_destinations(id,tenant_id)on delete restrict,foreign key(payment_method_id,tenant_id)references public.financial_payment_methods(id,tenant_id)on delete restrict,foreign key(branch_id,tenant_id)references public.branches(id,tenant_id)on delete restrict,foreign key(source_account_line_id,tenant_id)references public.account_move_lines(id,tenant_id)on delete restrict,foreign key(original_payment_id,tenant_id)references public.financial_payments(id,tenant_id)on delete restrict,
 foreign key(created_by,tenant_id)references public.tenant_users(id,tenant_id)on delete restrict,foreign key(submitted_by,tenant_id)references public.tenant_users(id,tenant_id)on delete restrict,foreign key(confirmed_by,tenant_id)references public.tenant_users(id,tenant_id)on delete restrict,foreign key(posted_by,tenant_id)references public.tenant_users(id,tenant_id)on delete restrict,foreign key(rejected_by,tenant_id)references public.tenant_users(id,tenant_id)on delete restrict,
 unique(tenant_id,refund_number),unique(tenant_id,idempotency_key),unique(tenant_id,posting_idempotency_key),unique(id,tenant_id),check(refund_number~'^RFD-[0-9]{4}-[0-9]{6,}$'),check(direction in('outbound','inbound')),check(amount>0 and amount=round(amount,2)),check(currency_code~'^[A-Z]{3}$'),check(source_type in('customer_receivable_credit','customer_advance','supplier_payable_debit','supplier_advance')),check((direction='outbound'and source_type in('customer_receivable_credit','customer_advance'))or(direction='inbound'and source_type in('supplier_payable_debit','supplier_advance'))),check(status in('draft','submitted','confirmed','rejected')),check(accounting_state in('unposted','posted','reversed')),check(btrim(reason)<>''),check(btrim(idempotency_key)<>''),check(request_fingerprint~'^[0-9a-f]{64}$'),check((status='draft'and submitted_by is null and confirmed_by is null and rejected_by is null)or(status='submitted'and submitted_by is not null and submitted_at is not null and confirmed_by is null and rejected_by is null)or(status='confirmed'and submitted_by is not null and confirmed_by is not null and confirmed_at is not null and rejected_by is null)or(status='rejected'and rejected_by is not null and rejected_at is not null and rejection_reason is not null)),check((accounting_state='unposted'and posted_by is null and posted_at is null and posting_idempotency_key is null)or(accounting_state in('posted','reversed')and posted_by is not null and posted_at is not null and posting_idempotency_key is not null))
);
create table public.financial_refund_accounting_links(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,refund_id uuid not null,account_move_id uuid not null,source_partial_reconcile_id uuid not null,entry_type text not null default'posting',created_by uuid not null,created_at timestamptz not null default now(),foreign key(refund_id,tenant_id)references public.financial_refunds(id,tenant_id)on delete restrict,foreign key(account_move_id,tenant_id)references public.account_moves(id,tenant_id)on delete restrict,foreign key(created_by,tenant_id)references public.tenant_users(id,tenant_id)on delete restrict,unique(tenant_id,refund_id,entry_type),unique(tenant_id,account_move_id),unique(tenant_id,source_partial_reconcile_id),check(entry_type in('posting','reversal')));
create table public.financial_refund_events(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,refund_id uuid not null,event_type text not null,from_status text,to_status text,actor_user_id uuid not null,reason text,metadata jsonb not null default'{}',created_at timestamptz not null default now(),foreign key(refund_id,tenant_id)references public.financial_refunds(id,tenant_id)on delete restrict,foreign key(actor_user_id,tenant_id)references public.tenant_users(id,tenant_id)on delete restrict,check(event_type in('created','submitted','confirmed','posted','rejected','accounting_reversed')),check(jsonb_typeof(metadata)='object'));

create or replace function public.next_financial_refund_number(p_tenant uuid)returns text language plpgsql security definer set search_path=pg_catalog,public as $$declare y int:=extract(year from current_date)::int;n bigint;begin insert into public.financial_refund_sequences(tenant_id,sequence_year,next_number)values(p_tenant,y,2)on conflict(tenant_id,sequence_year)do update set next_number=public.financial_refund_sequences.next_number+1,updated_at=now()returning next_number-1 into n;return'RFD-'||y||'-'||lpad(n::text,6,'0');end$$;

create or replace function public.resolve_financial_refund_source(p_tenant uuid,p_line uuid,p_partner uuid)returns jsonb language plpgsql stable security definer set search_path=pg_catalog,public as $$declare l public.account_move_lines%rowtype;m public.account_moves%rowtype;role text;stype text;dir text;begin
 select*into l from public.account_move_lines where id=p_line and tenant_id=p_tenant;select*into m from public.account_moves where id=l.move_id and tenant_id=p_tenant;
 if l.id is null or m.state<>'posted'or l.parent_state<>'posted'or l.partner_id is distinct from p_partner or l.amount_residual<=0 then raise exception using errcode='23514',message='REFUND_SOURCE_NOT_ELIGIBLE';end if;
 select f.functional_role into role from public.account_functional_accounts f where f.tenant_id=p_tenant and f.account_id=l.account_id and f.is_active and f.functional_role in('customer_receivable','customer_advance','supplier_payable','supplier_advance')limit 1;
 if role='customer_receivable'and l.credit>0 and l.debit=0 then stype:='customer_receivable_credit';dir:='outbound';elsif role='customer_advance'and l.credit>0 and l.debit=0 then stype:='customer_advance';dir:='outbound';elsif role='supplier_payable'and l.debit>0 and l.credit=0 then stype:='supplier_payable_debit';dir:='inbound';elsif role='supplier_advance'and l.debit>0 and l.credit=0 then stype:='supplier_advance';dir:='inbound';else raise exception using errcode='23514',message='REFUND_SOURCE_ACCOUNT_SEMANTICS_INVALID';end if;
 return jsonb_build_object('source_line_id',l.id,'source_type',stype,'direction',dir,'partner_id',l.partner_id,'account_id',l.account_id,'currency_code',l.currency_code,'residual_amount',l.amount_residual,'branch_id',m.branch_id,'move_id',m.id);
end$$;

create or replace function public.get_financial_refund_eligibility(p_tenant uuid,p_line uuid,p_partner uuid,p_amount numeric default null)returns jsonb language plpgsql stable security definer set search_path=pg_catalog,public as $$declare s jsonb;blockers jsonb:='[]';begin if public.current_tenant_id()<>p_tenant then raise exception using errcode='42501',message='REFUND_TENANT_ACCESS_DENIED';end if;begin s:=public.resolve_financial_refund_source(p_tenant,p_line,p_partner);exception when check_violation then return jsonb_build_object('refundable',false,'maximum_refundable_amount',0,'blockers',jsonb_build_array(sqlerrm));end;if p_amount is not null and(p_amount<=0 or p_amount<>round(p_amount,2))then blockers:=blockers||'"REFUND_AMOUNT_INVALID"'::jsonb;elsif p_amount is not null and p_amount>(s->>'residual_amount')::numeric then blockers:=blockers||'"REFUND_EXCEEDS_SOURCE_RESIDUAL"'::jsonb;end if;if not public.has_permission('financial.refund.create',p_tenant)then blockers:=blockers||'"REFUND_AUTHORIZATION_DENIED"'::jsonb;end if;return s||jsonb_build_object('refundable',jsonb_array_length(blockers)=0,'maximum_refundable_amount',(s->>'residual_amount')::numeric,'blockers',blockers);end$$;

create or replace function public.list_refundable_open_items(p_tenant uuid,p_partner uuid default null,p_limit int default 100)returns table(source_line_id uuid,source_type text,direction text,partner_id uuid,currency_code text,residual_amount numeric,branch_id uuid,move_id uuid)language plpgsql stable security definer set search_path=pg_catalog,public as $$declare r record;s jsonb;begin if public.current_tenant_id()<>p_tenant or not public.has_permission('financial.refund.create',p_tenant)then raise exception using errcode='42501',message='REFUND_AUTHORIZATION_DENIED';end if;for r in select l.id,l.partner_id from public.account_move_lines l join public.account_moves m on m.id=l.move_id and m.tenant_id=l.tenant_id where l.tenant_id=p_tenant and l.parent_state='posted'and m.state='posted'and l.amount_residual>0 and l.partner_id is not null and(p_partner is null or l.partner_id=p_partner)order by m.date,l.id limit least(greatest(coalesce(p_limit,100),1),500)loop begin s:=public.resolve_financial_refund_source(p_tenant,r.id,r.partner_id);return query select(s->>'source_line_id')::uuid,s->>'source_type',s->>'direction',(s->>'partner_id')::uuid,s->>'currency_code',(s->>'residual_amount')::numeric,(s->>'branch_id')::uuid,(s->>'move_id')::uuid;exception when check_violation then null;end;end loop;end$$;

create or replace function public.create_financial_refund(p_tenant uuid,p_source_line uuid,p_partner uuid,p_amount numeric,p_currency text,p_destination uuid,p_method uuid,p_reason text,p_idempotency text,p_branch uuid default null,p_original_payment uuid default null,p_reason_type text default null,p_notes text default null,p_source_app text default null,p_source_model text default null,p_source_id uuid default null)returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare s jsonb;existing public.financial_refunds%rowtype;rid uuid:=gen_random_uuid();actor uuid:=public.current_tenant_user_id();fp text;num text;begin
 if p_amount is null or p_amount<=0 or p_amount<>round(p_amount,2)then raise exception using errcode='22023',message='REFUND_AMOUNT_INVALID';end if;if nullif(btrim(coalesce(p_reason,'')),'')is null or nullif(btrim(coalesce(p_idempotency,'')),'')is null then raise exception using errcode='22023',message='REFUND_REASON_AND_IDEMPOTENCY_REQUIRED';end if;
 s:=public.resolve_financial_refund_source(p_tenant,p_source_line,p_partner);perform public.assert_financial_authorized(p_tenant,'financial.refund.create',(s->>'account_id')::uuid,'reconcile',(s->>'branch_id')::uuid,p_amount<=(s->>'residual_amount')::numeric);
 if upper(p_currency)<>s->>'currency_code'then raise exception using errcode='23514',message='REFUND_CURRENCY_MISMATCH';end if;if p_branch is distinct from(s->>'branch_id')::uuid and(s->>'branch_id')is not null then raise exception using errcode='23514',message='REFUND_SOURCE_BRANCH_MISMATCH';end if;
 fp:=encode(extensions.digest(jsonb_build_object('source',p_source_line,'partner',p_partner,'amount',p_amount,'currency',upper(p_currency),'destination',p_destination,'method',p_method,'reason',btrim(p_reason),'branch',p_branch,'original_payment',p_original_payment)::text,'sha256'),'hex');perform pg_advisory_xact_lock(hashtextextended('refund:create:'||p_tenant||':'||btrim(p_idempotency),0));select*into existing from public.financial_refunds where tenant_id=p_tenant and idempotency_key=btrim(p_idempotency);if found then if existing.request_fingerprint<>fp then raise exception using errcode='23505',message='REFUND_IDEMPOTENCY_PAYLOAD_MISMATCH';end if;return jsonb_build_object('refund_id',existing.id,'refund_number',existing.refund_number,'status',existing.status,'idempotent_replay',true);end if;
 if not exists(select 1 from public.partners where id=p_partner and tenant_id=p_tenant and active)or not exists(select 1 from public.financial_payment_methods where id=p_method and tenant_id=p_tenant and is_active)or not exists(select 1 from public.money_destinations where id=p_destination and tenant_id=p_tenant and status='active')then raise exception using errcode='23514',message='REFUND_PARTNER_METHOD_OR_DESTINATION_INVALID';end if;
 num:=public.next_financial_refund_number(p_tenant);perform set_config('app.financial_refund_contract',rid::text,true);insert into public.financial_refunds(id,tenant_id,refund_number,direction,amount,currency_code,partner_id,money_destination_id,payment_method_id,branch_id,source_type,source_account_line_id,original_payment_id,source_app,source_model,source_id,reason,reason_type,notes,created_by,idempotency_key,request_fingerprint)values(rid,p_tenant,num,s->>'direction',p_amount,upper(p_currency),p_partner,p_destination,p_method,coalesce(p_branch,(s->>'branch_id')::uuid),s->>'source_type',p_source_line,p_original_payment,p_source_app,p_source_model,p_source_id,btrim(p_reason),p_reason_type,p_notes,actor,btrim(p_idempotency),fp);insert into public.financial_refund_events(tenant_id,refund_id,event_type,to_status,actor_user_id,reason,metadata)values(p_tenant,rid,'created','draft',actor,p_reason,jsonb_build_object('source',s,'amount',p_amount,'destination_id',p_destination));return jsonb_build_object('refund_id',rid,'refund_number',num,'status','draft','source_type',s->>'source_type','direction',s->>'direction','idempotent_replay',false);end$$;

create or replace function public.transition_financial_refund(p_tenant uuid,p_refund uuid,p_action text,p_reason text default null)returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare r public.financial_refunds%rowtype;actor uuid:=public.current_tenant_user_id();next text;perm text;begin select*into r from public.financial_refunds where id=p_refund and tenant_id=p_tenant for update;if not found then raise exception using errcode='P0002',message='FINANCIAL_REFUND_NOT_FOUND';end if;if p_action='submit'and r.status='draft'then next:='submitted';perm:='financial.refund.submit';elsif p_action='confirm'and r.status='submitted'then next:='confirmed';perm:='financial.refund.confirm';elsif p_action='reject'and r.status in('draft','submitted')then next:='rejected';perm:='financial.refund.confirm';if nullif(btrim(coalesce(p_reason,'')),'')is null then raise exception using errcode='22023',message='REFUND_REJECTION_REASON_REQUIRED';end if;else raise exception using errcode='23514',message='REFUND_LIFECYCLE_TRANSITION_INVALID';end if;perform public.assert_financial_authorized(p_tenant,perm,null,null,r.branch_id,true);perform set_config('app.financial_refund_contract',r.id::text,true);if next='submitted'then update public.financial_refunds set status=next,submitted_by=actor,submitted_at=now(),updated_at=now()where id=r.id;elsif next='confirmed'then update public.financial_refunds set status=next,confirmed_by=actor,confirmed_at=now(),updated_at=now()where id=r.id;else update public.financial_refunds set status=next,rejected_by=actor,rejected_at=now(),rejection_reason=btrim(p_reason),updated_at=now()where id=r.id;end if;insert into public.financial_refund_events(tenant_id,refund_id,event_type,from_status,to_status,actor_user_id,reason)values(p_tenant,r.id,next,r.status,next,actor,p_reason);return jsonb_build_object('refund_id',r.id,'status',next);end$$;
create or replace function public.submit_financial_refund(p_tenant uuid,p_refund uuid)returns jsonb language sql security definer set search_path=pg_catalog,public as $$select public.transition_financial_refund(p_tenant,p_refund,'submit',null)$$;
create or replace function public.confirm_financial_refund(p_tenant uuid,p_refund uuid)returns jsonb language sql security definer set search_path=pg_catalog,public as $$select public.transition_financial_refund(p_tenant,p_refund,'confirm',null)$$;
create or replace function public.reject_financial_refund(p_tenant uuid,p_refund uuid,p_reason text)returns jsonb language sql security definer set search_path=pg_catalog,public as $$select public.transition_financial_refund(p_tenant,p_refund,'reject',p_reason)$$;

create or replace function public.post_financial_refund(p_tenant uuid,p_refund uuid,p_idempotency text)returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare r public.financial_refunds%rowtype;s jsonb;method public.financial_payment_methods%rowtype;dst record;actor uuid:=public.current_tenant_user_id();mid uuid:=gen_random_uuid();refund_line uuid:=gen_random_uuid();cash_line uuid:=gen_random_uuid();partial uuid:=gen_random_uuid();access text;begin
 if nullif(btrim(coalesce(p_idempotency,'')),'')is null then raise exception using errcode='22023',message='REFUND_POST_IDEMPOTENCY_REQUIRED';end if;perform pg_advisory_xact_lock(hashtextextended('refund:post:'||p_tenant||':'||p_refund,0));select*into r from public.financial_refunds where id=p_refund and tenant_id=p_tenant for update;if not found then raise exception using errcode='P0002',message='FINANCIAL_REFUND_NOT_FOUND';end if;if r.accounting_state='posted'then if r.posting_idempotency_key<>btrim(p_idempotency)then raise exception using errcode='23505',message='REFUND_POST_IDEMPOTENCY_MISMATCH';end if;return jsonb_build_object('refund_id',r.id,'account_move_id',(select account_move_id from public.financial_refund_accounting_links where refund_id=r.id and entry_type='posting'),'accounting_state','posted','idempotent_replay',true);end if;
 perform public.assert_financial_authorized(p_tenant,'financial.refund.post',null,null,r.branch_id,r.status='confirmed'and r.accounting_state='unposted');s:=public.resolve_financial_refund_source(p_tenant,r.source_account_line_id,r.partner_id);perform 1 from public.account_move_lines where id=r.source_account_line_id for update;s:=public.resolve_financial_refund_source(p_tenant,r.source_account_line_id,r.partner_id);if r.amount>(s->>'residual_amount')::numeric then raise exception using errcode='23514',message='REFUND_EXCEEDS_SOURCE_RESIDUAL';end if;if r.currency_code<>s->>'currency_code'or r.source_type<>s->>'source_type'or r.direction<>s->>'direction'then raise exception using errcode='23514',message='REFUND_SOURCE_CHANGED_OR_CURRENCY_MISMATCH';end if;
 select*into method from public.financial_payment_methods where id=r.payment_method_id and tenant_id=p_tenant and is_active;if not found or method.requires_confirmation then raise exception using errcode='23514',message='REFUND_METHOD_REQUIRES_CLEARING_OR_IS_INVALID';end if;access:=case when r.direction='outbound'then'pay_out'else'confirm'end;select*into dst from public.resolve_money_destination_for_action(p_tenant,r.money_destination_id,'financial.refund.post',access,r.branch_id,array(select destination_type from public.financial_payment_method_destination_types where method_type=method.method_type));
 insert into public.account_moves(id,tenant_id,branch_id,journal_id,name,move_type,partner_id,invoice_date,date,amount_total,state,ref,notes,pay_method,currency_code,created_by)values(mid,p_tenant,r.branch_id,dst.journal_id,'REFUND-'||r.refund_number,case when r.direction='outbound'then'cash_out'else'cash_in'end,r.partner_id,current_date,current_date,r.amount,'posted','financial_refund:'||r.id,r.reason,method.semantic_key,r.currency_code,actor);
 if r.direction='outbound'then insert into public.account_move_lines(id,tenant_id,move_id,account_id,partner_id,label,quantity,unit_price,debit,credit,line_type,is_reconciled,amount_residual,amount_residual_currency,parent_state,currency_code,created_by)values(refund_line,p_tenant,mid,(s->>'account_id')::uuid,r.partner_id,r.refund_number||' source',1,r.amount,r.amount,0,'open_item',false,r.amount,r.amount,'posted',r.currency_code,actor),(cash_line,p_tenant,mid,dst.ledger_account_id,null,r.refund_number||' money',1,r.amount,0,r.amount,'liquidity',true,0,0,'posted',r.currency_code,actor);insert into public.account_partial_reconcile(id,tenant_id,debit_move_id,credit_move_id,amount,max_date,created_by)values(partial,p_tenant,refund_line,r.source_account_line_id,r.amount,current_date,actor);
 else insert into public.account_move_lines(id,tenant_id,move_id,account_id,partner_id,label,quantity,unit_price,debit,credit,line_type,is_reconciled,amount_residual,amount_residual_currency,parent_state,currency_code,created_by)values(cash_line,p_tenant,mid,dst.ledger_account_id,null,r.refund_number||' money',1,r.amount,r.amount,0,'liquidity',true,0,0,'posted',r.currency_code,actor),(refund_line,p_tenant,mid,(s->>'account_id')::uuid,r.partner_id,r.refund_number||' source',1,r.amount,0,r.amount,'open_item',false,r.amount,r.amount,'posted',r.currency_code,actor);insert into public.account_partial_reconcile(id,tenant_id,debit_move_id,credit_move_id,amount,max_date,created_by)values(partial,p_tenant,r.source_account_line_id,refund_line,r.amount,current_date,actor);end if;
 perform public.accounting_assert_move_balanced(mid);perform set_config('app.financial_refund_contract',r.id::text,true);insert into public.financial_refund_accounting_links(tenant_id,refund_id,account_move_id,source_partial_reconcile_id,created_by)values(p_tenant,r.id,mid,partial,actor);update public.financial_refunds set accounting_state='posted',posted_by=actor,posted_at=now(),posting_idempotency_key=btrim(p_idempotency),updated_at=now()where id=r.id;insert into public.financial_refund_events(tenant_id,refund_id,event_type,from_status,to_status,actor_user_id,reason,metadata)values(p_tenant,r.id,'posted',r.status,r.status,actor,r.reason,jsonb_build_object('account_move_id',mid,'partial_reconcile_id',partial));return jsonb_build_object('refund_id',r.id,'refund_number',r.refund_number,'account_move_id',mid,'partial_reconcile_id',partial,'accounting_state','posted','idempotent_replay',false);end$$;

create or replace function public.guard_financial_refund()returns trigger language plpgsql set search_path=pg_catalog,public as $$begin if tg_op='DELETE'then raise exception using errcode='23514',message='FINANCIAL_REFUND_IMMUTABLE';end if;if current_setting('app.financial_refund_contract',true)=coalesce(new.id,old.id)::text then return new;end if;raise exception using errcode='42501',message='FINANCIAL_REFUND_REQUIRES_CANONICAL_CONTRACT';end$$;
create or replace function public.guard_financial_refund_child()returns trigger language plpgsql set search_path=pg_catalog,public as $$begin if tg_op<>'INSERT'then raise exception using errcode='23514',message='FINANCIAL_REFUND_AUDIT_IMMUTABLE';end if;if current_setting('app.financial_refund_contract',true)=new.refund_id::text then return new;end if;raise exception using errcode='42501',message='FINANCIAL_REFUND_AUDIT_REQUIRES_CONTRACT';end$$;
create trigger financial_refunds_guard before insert or update or delete on public.financial_refunds for each row execute function public.guard_financial_refund();create trigger financial_refund_links_guard before insert or update or delete on public.financial_refund_accounting_links for each row execute function public.guard_financial_refund_child();create trigger financial_refund_events_guard before insert or update or delete on public.financial_refund_events for each row execute function public.guard_financial_refund_child();

alter table public.financial_refund_sequences enable row level security;alter table public.financial_refunds enable row level security;alter table public.financial_refund_accounting_links enable row level security;alter table public.financial_refund_events enable row level security;revoke all on public.financial_refund_sequences,public.financial_refunds,public.financial_refund_accounting_links,public.financial_refund_events from public,anon,authenticated;grant select on public.financial_refunds,public.financial_refund_accounting_links,public.financial_refund_events to authenticated;create policy financial_refunds_read on public.financial_refunds for select to authenticated using(tenant_id=public.current_tenant_id()and(public.has_permission('financial.refund.create',tenant_id)or public.has_permission('financial.refund.submit',tenant_id)or public.has_permission('financial.refund.confirm',tenant_id)or public.has_permission('financial.refund.post',tenant_id)));create policy financial_refund_links_read on public.financial_refund_accounting_links for select to authenticated using(tenant_id=public.current_tenant_id()and exists(select 1 from public.financial_refunds r where r.id=refund_id and r.tenant_id=tenant_id));create policy financial_refund_events_read on public.financial_refund_events for select to authenticated using(tenant_id=public.current_tenant_id()and exists(select 1 from public.financial_refunds r where r.id=refund_id and r.tenant_id=tenant_id));
revoke all on function public.next_financial_refund_number(uuid),public.resolve_financial_refund_source(uuid,uuid,uuid),public.transition_financial_refund(uuid,uuid,text,text),public.guard_financial_refund(),public.guard_financial_refund_child()from public,anon,authenticated;revoke all on function public.get_financial_refund_eligibility(uuid,uuid,uuid,numeric),public.list_refundable_open_items(uuid,uuid,int),public.create_financial_refund(uuid,uuid,uuid,numeric,text,uuid,uuid,text,text,uuid,uuid,text,text,text,text,uuid),public.submit_financial_refund(uuid,uuid),public.confirm_financial_refund(uuid,uuid),public.reject_financial_refund(uuid,uuid,text),public.post_financial_refund(uuid,uuid,text)from public,anon;grant execute on function public.get_financial_refund_eligibility(uuid,uuid,uuid,numeric),public.list_refundable_open_items(uuid,uuid,int),public.create_financial_refund(uuid,uuid,uuid,numeric,text,uuid,uuid,text,text,uuid,uuid,text,text,text,text,uuid),public.submit_financial_refund(uuid,uuid),public.confirm_financial_refund(uuid,uuid),public.reject_financial_refund(uuid,uuid,text),public.post_financial_refund(uuid,uuid,text)to authenticated;
comment on table public.financial_refunds is'Canonical money refund business event. It consumes an existing refundable open-item residual and is neither an accounting reversal nor a credit note.';
commit;
