export { PlatformShell } from './shell/PlatformShell';
export { PlatformTopBar } from './shell/PlatformTopBar';
export { PlatformContent } from './shell/PlatformContent';
export { usePlatformShell, useOptionalPlatformShell } from './shell/PlatformShellContext';
export { resolveShellPolicy, DEFAULT_SHELL_POLICY } from './shell/shellPolicy.js';
export { PageLayout } from './page/PageLayout';
export { PageHeader } from './page/PageHeader';
export { PageState } from './page/PageState';
export { PlatformSideSheet } from './surfaces/PlatformSideSheet';
export { PLATFORM_SURFACE_LAYERS } from './surfaces/platformSideSheetContract.js';
export { AppNavigation } from './navigation/AppNavigation';
export { AppSidebar } from './navigation/AppSidebar';
export { MobileAppNavigation } from './navigation/MobileAppNavigation';
export { createNavigationRegistry, validateAppRegistration } from './navigation/navigationRegistry.js';
export { resolveNavigationMode, resolveNavigationItems, resolveActiveNavigationItem } from './navigation/navigationResolver.js';
export { adaptLegacyInstalledApp, adaptLegacyNavigationItems } from './navigation/legacyNavigationAdapter.js';
export { createRouteManifest } from './routing/routeManifest.js';
export { resolveBreadcrumbs } from './routing/breadcrumbResolver.js';
export { createLegacyRedirectAdapter } from './routing/legacyRedirects.js';
export { createPlatformAccessSnapshot, adaptLegacyAppContext } from './access/platformAccessAdapter.js';
